.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-land-push 1  batten 
.SH NAME
batten\-land\-push \- Push this branch to its own ref, under receive\-pack\*(Aqs compare\-and\-swap
.SH SYNOPSIS
\fBbatten land push\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Push this branch to its own ref, under receive\-pack\*(Aqs compare\-and\-swap
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
