.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-lease-authorises 1  batten 
.SH NAME
batten\-lease\-authorises \- May this branch spend a matrix right now?
.SH SYNOPSIS
\fBbatten lease authorises\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIbranch\fR> 
.SH DESCRIPTION
May this branch spend a matrix right now?
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIbranch\fR>
The branch being asked about
