.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-land-fast-forward 1  batten 
.SH NAME
batten\-land\-fast\-forward \- Ask this head\*(Aqs pull request to fast\-forward, and read the answer that request got
.SH SYNOPSIS
\fBbatten land fast\-forward\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Ask this head\*(Aqs pull request to fast\-forward, and read the answer that request got
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
