.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-doctor 1  batten 
.SH NAME
batten\-doctor \- Diagnose whether Batten can run in this repository
.SH SYNOPSIS
\fBbatten doctor\fR [\fB\-J\fR|\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Diagnose whether Batten can run in this repository
.SH OPTIONS
.TP
\fB\-J\fR, \fB\-\-json\fR
Emit byte\-stable JSON instead of pointer lines
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
