.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-perf-measure 1  batten 
.SH NAME
batten\-perf\-measure \- Measure this binary\*(Aqs invocation cost on every path and print one record per path
.SH SYNOPSIS
\fBbatten perf measure\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Measure this binary\*(Aqs invocation cost on every path and print one record per path
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
