.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-attribution-identity 1  batten 
.SH NAME
batten\-attribution\-identity \- Set this clone\*(Aqs repo\-local git identity when it is unset or denied
.SH SYNOPSIS
\fBbatten attribution identity\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Set this clone\*(Aqs repo\-local git identity when it is unset or denied
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
