.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-engine-digest 1  batten 
.SH NAME
batten\-engine\-digest \- Print the source digest of this tree\*(Aqs tracked engine inputs, the value a source pin names
.SH SYNOPSIS
\fBbatten engine digest\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Print the source digest of this tree\*(Aqs tracked engine inputs, the value a source pin names
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
