.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-lease-acquire 1  batten 
.SH NAME
batten\-lease\-acquire \- Take the lease, waiting out a live holder and reaping a dead one
.SH SYNOPSIS
\fBbatten lease acquire\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIbranch\fR> 
.SH DESCRIPTION
Take the lease, waiting out a live holder and reaping a dead one
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIbranch\fR>
The branch being asked about
