.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-record-plan 1  batten 
.SH NAME
batten\-record\-plan \- Record this branch\*(Aqs plan, read as `<id> <status>` lines on stdin
.SH SYNOPSIS
\fBbatten record plan\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Record this branch\*(Aqs plan, read as `<id> <status>` lines on stdin
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
