.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-provision-status 1  "batten 0.0.61" 
.SH NAME
batten\-provision\-status \- Report which provisioned tools do not match the manifest
.SH SYNOPSIS
\fBbatten provision status\fR [\fB\-J\fR|\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Report which provisioned tools do not match the manifest
.SH OPTIONS
.TP
\fB\-J\fR, \fB\-\-json\fR
Emit byte\-stable JSON instead of pointer lines
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.0.61
