.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-config-epoch 1  "batten 0.0.61" 
.SH NAME
batten\-config\-epoch \- Print the content hash of the governing config surface
.SH SYNOPSIS
\fBbatten config epoch\fR [\fB\-J\fR|\fB\-\-json\fR] [\fB\-\-no\-cache\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Print the content hash of the governing config surface
.SH OPTIONS
.TP
\fB\-J\fR, \fB\-\-json\fR
Emit byte\-stable JSON instead of pointer lines
.TP
\fB\-\-no\-cache\fR
Recompute the epoch from the tracked files\*(Aq bytes, ignoring the cached value
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.0.61
