.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-record-census-tally 1  batten 
.SH NAME
batten\-record\-census\-tally \- Count every recorded replacement by what it interrupted
.SH SYNOPSIS
\fBbatten record census tally\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Count every recorded replacement by what it interrupted
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
