.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-generate-man 1  batten 
.SH NAME
batten\-generate\-man \- Emit the roff man page for one command, on stdout
.SH SYNOPSIS
\fBbatten generate man\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIcommand\fR] 
.SH DESCRIPTION
Emit the roff man page for one command, on stdout
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIcommand\fR]
The root\-relative command path to document (\*(Aqconfig show\*(Aq); omit for the root page
