.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-generate-completions 1  "batten 0.0.61" 
.SH NAME
batten\-generate\-completions \- Emit the shell completion script for one shell
.SH SYNOPSIS
\fBbatten generate completions\fR <\fB\-\-shell\fR> [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Emit the shell completion script for one shell
.SH OPTIONS
.TP
\fB\-\-shell\fR
The shell whose completion script to emit
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
bash
.IP \(bu 2
elvish
.IP \(bu 2
fish
.IP \(bu 2
powershell
.IP \(bu 2
zsh
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.0.61
