.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-pr-closes 1  batten 
.SH NAME
batten\-pr\-closes \- Whether a pull request\*(Aqs body still closes a tracker key, asked at the last moment
.SH SYNOPSIS
\fBbatten pr closes\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIpr\fR> 
.SH DESCRIPTION
Whether a pull request\*(Aqs body still closes a tracker key, asked at the last moment
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIpr\fR>
The pull request number this verb is about
