.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-state-record 1  "batten 0.0.61" 
.SH NAME
batten\-state\-record \- Record this ref\*(Aqs findings into the store, and GC instances whose ref is gone
.SH SYNOPSIS
\fBbatten state record\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Record this ref\*(Aqs findings into the store, and GC instances whose ref is gone
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.0.61
