.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-claim-race 1  batten 
.SH NAME
batten\-claim\-race \- Refuse a claim a different open pull request already carries, judged by head SHA
.SH SYNOPSIS
\fBbatten claim race\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Refuse a claim a different open pull request already carries, judged by head SHA
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
