.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-state-migrate 1  "batten 0.0.61" 
.SH NAME
batten\-state\-migrate \- Upgrade the findings store to this binary\*(Aqs record version
.SH SYNOPSIS
\fBbatten state migrate\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Upgrade the findings store to this binary\*(Aqs record version
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.0.61
