.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-lease-held 1  batten 
.SH NAME
batten\-lease\-held \- Is this clone\*(Aqs lease still held, with a beat of margin to act on?
.SH SYNOPSIS
\fBbatten lease held\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Is this clone\*(Aqs lease still held, with a beat of margin to act on?
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
