.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-record-closes 1  batten 
.SH NAME
batten\-record\-closes \- Record which rows this branch\*(Aqs pull request body closes, read on stdin
.SH SYNOPSIS
\fBbatten record closes\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Record which rows this branch\*(Aqs pull request body closes, read on stdin
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
