.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-land-lap 1  batten 
.SH NAME
batten\-land\-lap \- Drive the whole lap and lap again on any refusal a rebase would clear
.SH SYNOPSIS
\fBbatten land lap\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIreference\fR> 
.SH DESCRIPTION
Drive the whole lap and lap again on any refusal a rebase would clear
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIreference\fR>
The remote reference to replay onto
