.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-generate-markdown 1  batten 
.SH NAME
batten\-generate\-markdown \- Emit the whole command surface as one markdown reference, on stdout
.SH SYNOPSIS
\fBbatten generate markdown\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Emit the whole command surface as one markdown reference, on stdout
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
