.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-pr-ensure 1  batten 
.SH NAME
batten\-pr\-ensure \- File the row and link it, doing whatever this tick can and saying what it did
.SH SYNOPSIS
\fBbatten pr ensure\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIpr\fR> 
.SH DESCRIPTION
File the row and link it, doing whatever this tick can and saying what it did
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIpr\fR>
The pull request number this verb is about
