.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-lease-release 1  batten 
.SH NAME
batten\-lease\-release \- Hand the lease back, leaving a tombstone rather than deleting the ref
.SH SYNOPSIS
\fBbatten lease release\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Hand the lease back, leaving a tombstone rather than deleting the ref
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
