.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-defects-add 1  "batten 0.0.61" 
.SH NAME
batten\-defects\-add \- Append defect records read as JSONL on stdin
.SH SYNOPSIS
\fBbatten defects add\fR [\fB\-n\fR|\fB\-\-dry\-run\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Append defect records read as JSONL on stdin
.SH OPTIONS
.TP
\fB\-n\fR, \fB\-\-dry\-run\fR
Preview what would be applied, writing nothing
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.0.61
