.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-receipt-record 1  batten 
.SH NAME
batten\-receipt\-record \- Record that the named check concluded pass against the current HEAD
.SH SYNOPSIS
\fBbatten receipt record\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIcheck\fR> 
.SH DESCRIPTION
Record that the named check concluded pass against the current HEAD
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIcheck\fR>
The check whose conclusion is being recorded
