.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-perf-record 1  batten 
.SH NAME
batten\-perf\-record \- Append a measurement to the trunk\*(Aqs invocation\-cost series, read as `perf measure` records on stdin
.SH SYNOPSIS
\fBbatten perf record\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Append a measurement to the trunk\*(Aqs invocation\-cost series, read as `perf measure` records on stdin
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
