.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-record-census-record-boot 1  batten 
.SH NAME
batten\-record\-census\-record\-boot \- Record this container\*(Aqs boot, once
.SH SYNOPSIS
\fBbatten record census record\-boot\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Record this container\*(Aqs boot, once
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
