.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-provision-status 1  batten 
.SH NAME
batten\-provision\-status \- Report which provisioned tools do not match the manifest
.SH SYNOPSIS
\fBbatten provision status\fR [\fB\-J\fR|\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Report which provisioned tools do not match the manifest
.SH OPTIONS
.TP
\fB\-J\fR, \fB\-\-json\fR
Emit byte\-stable JSON instead of pointer lines
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
