.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-engine-update 1  batten 
.SH NAME
batten\-engine\-update \- Install the engine this config pins over the running binary, from its release or from this tree
.SH SYNOPSIS
\fBbatten engine update\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Install the engine this config pins over the running binary, from its release or from this tree
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
