.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-mutate-census 1  batten 
.SH NAME
batten\-mutate\-census \- Report every gate in the tree that is neither mutation\-enforced nor carrying a filed exemption
.SH SYNOPSIS
\fBbatten mutate census\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Report every gate in the tree that is neither mutation\-enforced nor carrying a filed exemption
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
