.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-pr-file 1  batten 
.SH NAME
batten\-pr\-file \- Open the mirror issue a bot\*(Aqs pull request implies, and report its number
.SH SYNOPSIS
\fBbatten pr file\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIpr\fR> 
.SH DESCRIPTION
Open the mirror issue a bot\*(Aqs pull request implies, and report its number
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIpr\fR>
The pull request number this verb is about
