.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-lease-reserve 1  batten 
.SH NAME
batten\-lease\-reserve \- Take the one slot behind the current holder
.SH SYNOPSIS
\fBbatten lease reserve\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIbranch\fR> 
.SH DESCRIPTION
Take the one slot behind the current holder
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIbranch\fR>
The branch being asked about
