.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-attribution-signing 1  batten 
.SH NAME
batten\-attribution\-signing \- Switch signing off in this clone when its signer cannot be verified or reproduced
.SH SYNOPSIS
\fBbatten attribution signing\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Switch signing off in this clone when its signer cannot be verified or reproduced
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
