.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-doctor 1  "batten 0.0.61" 
.SH NAME
batten\-doctor \- Diagnose whether Batten can run in this repository
.SH SYNOPSIS
\fBbatten doctor\fR [\fB\-J\fR|\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Diagnose whether Batten can run in this repository
.SH OPTIONS
.TP
\fB\-J\fR, \fB\-\-json\fR
Emit byte\-stable JSON instead of pointer lines
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.0.61
