.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH batten-state-list 1  "batten 0.0.61" 
.SH NAME
batten\-state\-list \- List stored findings and the refs they were observed in
.SH SYNOPSIS
\fBbatten state list\fR [\fB\-J\fR|\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
List stored findings and the refs they were observed in
.SH OPTIONS
.TP
\fB\-J\fR, \fB\-\-json\fR
Emit byte\-stable JSON instead of pointer lines
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.0.61
