#!/usr/bin/env bash
# The git hook body this clone installs, dispatched by the name it is invoked as
# (CLOUD-476). `.git/hooks/pre-commit` and `.git/hooks/commit-msg` are symlinks
# to this file, so `${0##*/}` names the hook hk is being asked to run.
#
# WHY THIS IS CHECKED IN RATHER THAN GENERATED BY `hk install`. Two properties
# below are load-bearing and neither is expressible in the hook hk writes, which
# is `exec hk run <hook>` and nothing else:
#
#   * `hk` is resolved through mise (`mise exec --`), never bare. mise's shims
#     are not on PATH in a cloud container, so the generated form fails every
#     commit with `hk: not found` — the exact failure that made
#     `.claude/hooks/session-start.sh` decline to install a hook at all.
#   * THE GATE MUST NOT RE-ENTER ITSELF. `doctor` runs inside the gate
#     (`test:bats` depends on it, mise.toml), so anything inside the gate that
#     executes this hook re-enters `hk run pre-commit`, which runs `test:bats`,
#     which runs `doctor`, which executes the hook: unbounded recursion with no
#     exit condition. Measured 2026-08-12 — it hung a `git commit`, and the
#     session that hit it burned its remaining container lifetime polling the
#     hung commit and died with the fix uncommitted.
#
# Being checked in also makes the body testable directly (tests/git-hook.bats)
# instead of only through a hook installation.
set -uo pipefail

hook=${0##*/}

# --- probe mode ---------------------------------------------------------------
#
# The one question a caller inside the gate may ask: does this hook resolve its
# runner in THIS environment? That is what `doctor` needs to assert — "present
# but cannot resolve `hk`" is the failure a file-existence check reports as
# healthy — and it is one cheap call, not a gate run. Answering it here rather
# than letting doctor run the real hook is what keeps the assertion from being
# the recursion above.
if [ -n "${BATTEN_HOOK_PROBE:-}" ]; then
	exec mise exec -- hk --version
fi

# --- the re-entrancy refusal --------------------------------------------------
#
# A PID, not a boolean: a boolean left in the environment by a gate run that has
# since died would disarm the next legitimate one, and this must fail toward
# running the gate. The marker can only reach a process that descends from the
# gate that exported it, so a live PID here means an ancestor is mid-gate; a
# dead one means we are an orphan of a gate that is gone, and the commit in hand
# is a real one. Same discipline as `land`'s orphan tether (CLOUD-432).
#
# A refusal, not a silent skip: a caller inside the gate that wanted the gate is
# asking for the hang, and the whole point is that it now gets an exit code
# instead. Exit 9 rather than 1 so the suite — and a human reading a failed
# commit — can tell "refused to recurse" from "the gate failed".
if [ -n "${BATTEN_GATE_PID:-}" ] && kill -0 "$BATTEN_GATE_PID" 2>/dev/null; then
	printf '::error:: %s: the gate is already running (pid %s); refusing to run it again from inside itself.\nA task that runs inside the gate must not execute this hook. To ask whether the hook resolves its runner, set BATTEN_HOOK_PROBE=1 — one call, no gate run.\n' \
		"$hook" "$BATTEN_GATE_PID" >&2
	exit 9
fi

export BATTEN_GATE_PID=$$

# --- the two-tier gate -------------------------------------------------------
#
# `--profile '!slow'` is the ONE place the expensive tier is switched off
# (CLOUD-509). hk.pkl enables `slow` at the config layer, so every other entry
# point — `hk check --all` via `mise run ci`, `hk fix --all`, CI — runs the full
# gate by default; this line is the single deliberate exception, on the one path
# that is paid per commit.
#
# It is a CLI flag rather than `Hook.env` in hk.pkl because hook env cannot do
# this: `Hook` has no `profiles` field, and hook env is merged into each step's
# CHILD process environment, never into hk's own settings. Profiles resolve once
# at startup, and CLI is the top of that ladder with replace semantics — so this
# value wholly supplants hk.pkl's for this process and nothing else.
#
# `commit-msg` gets it too and is unaffected: its only step is a grep, which
# declares no profile and therefore always runs.
mise exec -- hk run "$hook" --profile '!slow' "$@"
