# A migration that touches an authored shell rule retires it, or it does not land.
#
# CLOUD-1059, and it is a PREREQUISITE rather than a cleanup: CLOUD-843's campaign
# is retiring 144 shell programs and 161 bats suites onto the policy engine, and
# the failure that campaign cannot survive is a wave that EDITS a shell gate
# instead of replacing it. That reads as progress in every sensor the tree has —
# `bash-surface-not-growing` counts programs and an edit changes none, and
# `bats-tests-not-deleted` counts `@test` cases and an edit changes none — so the
# corpus stays exactly as large while the campaign reports movement.
#
# THE LEDGER IS CLOUD-908'S, NOT A SECOND MANIFEST. `[rule.conserves]` already
# declares the arms (`// carried:`, `// subsumed:`, `// changed:`) and already
# says where they live (`crates/batten/tests/*.rs`). This module reads that same
# declaration one level up: 908 conserves the CASES inside a dying suite, and this
# conserves the FILE. A second inventory of which shell programs exist is exactly
# the hand-maintained census CLOUD-929 measured going stale, so there is none.
#
# ─── WHAT A RETIREMENT ROW LOOKS LIKE ────────────────────────────────────────
#
#   // carried: mise-tasks/prose-only-check.sh policy/prose-only.rego crates/batten/tests/prose_only.rs
#
# The marker, the path that died, then its successors. Two obligations, because
# either alone is satisfiable by a port that does nothing: at least one successor
# must be a POLICY SURFACE (`policy/*.rego` or `crates/batten/src/*.rs`), and at
# least one must be a COMPILED-BINARY TEST (`crates/batten/tests/*.rs`). A port
# naming only a module has no evidence it works; a port naming only a test has
# nothing under test.
#
# ─── THE THREE REFUSALS, AND WHY EDIT IS THE LOAD-BEARING ONE ────────────────
#
# ADDED is the obvious one and the cheapest to satisfy honestly. EDITED is the one
# this module exists for: it is indistinguishable from ordinary maintenance to
# every other gate in the tree, and it is how a migration silently does not
# happen. DELETED-WITHOUT-A-MAPPING is CLOUD-908's shape at file granularity —
# the deletion is admitted, and nothing records what now holds the predicate.
#
# ─── WHAT THIS DOES NOT DECIDE, STATED RATHER THAN DISCOVERED ────────────────
#
# **A deleted path is classified BY PATH, never by its content.** It has no
# content at head — that is what deleted means — and reading the base tree to
# re-classify it would make the fact carry the bytes of a file the diff already
# says is gone. So `mise-tasks/**` minus the explicitly non-shell paths is the
# test on the deleted side, and a shebang/`#MISE description=` test on the added
# and edited sides where the lines exist. The asymmetry is deliberate and it errs
# toward DEMANDING a mapping, which is the safe direction: the cost of a wrong
# refusal is one ledger row, and the cost of a wrong pass is an unrecorded port.
#
# **Whether the successor actually holds the predicate is not decidable here.**
# That a named module exists and a named test exists is checkable; that the test
# discriminates is CLOUD-1020's question and `mutant`'s, and a gate over it would
# be the model verdict non-negotiable rule 3 forbids.
#
# **Generated artifacts are excluded by path and never judged.** Batten's own
# completions are derived output regenerated by `mise run completions`; treating
# one as an authored shell rule would refuse every change that regenerates them.
#
#MUTANT shell-added-unchecked|s@delta.added@[]@|an added authored shell rule is refused
#MUTANT shell-edited-unchecked|s@delta.edited@[]@|an edited-in-place shell rule is refused
#MUTANT shell-deletion-unmapped|s@count(arms_for(path)) == 1@true@|a deleted shell rule with no mapping is refused
#MUTANT shell-mapping-not-unique|s@count(arms_for(path)) == 1@count(arms_for(path)) > 0@|a deleted rule carrying two arms is refused
#MUTANT shell-successor-unproven|s@has_binary_test(path)@true@|a mapping naming no compiled-binary test is refused
#
#MUTANT-EXEMPT CLOUD-931|no `tests/shell-retirement.bats` exists and none may: this row's whole subject is that a migration ships no new bats suite, so a suite named for it would be the thing it refuses. `mutant` resolves a gate's suite as `tests/$gate.bats`, so there is no named case a mutation could turn red. The second tier is `crates/batten/tests/shell_retirement.rs`, which drives the compiled binary and is the stronger evidence

# METADATA
# description: |
#   Bound to the TREE surface: `scope = "tree"`, so it reads the tree document
#   and never the mediated `{call, facts}` shape.
#   THE BRACKETS ARE NOT STYLE: the schema file carries a hyphen, so the dotted
#   form is a parse error reported as `invalid schema reference`.
#   THIS BLOCK IS YAML AND MUST STAY THE LAST COMMENT BLOCK BEFORE `package`.
# schemas:
#   - input: schema["policy-input.schema"]
package batten.shell_retirement

import rego.v1

rules contains "shell-rule-retired"

# ---------------------------------------------------------------------------
# The changed-file set, and the could-not-look channel.
# ---------------------------------------------------------------------------

# `input.tree.base-delta` is NULL when the base rev did not resolve, and `null`
# is not `undefined` — `not input.tree["base-delta"]` would be false for it, the
# exact slip CLOUD-701's review caught in `spawn-adapters`. So the delta is bound
# through a rule that holds only for an object, and every predicate below is
# undefined without it rather than vacuously clean.
delta := d if {
	d := input.tree["base-delta"]
	is_object(d)
}

# ---------------------------------------------------------------------------
# Which changed paths are the ones this row governs.
# ---------------------------------------------------------------------------

# A bats suite, on either side of the diff: the extension IS the declaration.
is_bats(path) if {
	startswith(path, "tests/")
	endswith(path, ".bats")
}

# Under `mise-tasks/`, excluding the paths that are not shell at all. Listed
# rather than pattern-matched because the set is small, closed, and a wrong
# guess here silently drops a program out of the campaign's scope.
under_mise_tasks(path) if {
	startswith(path, "mise-tasks/")
	not endswith(path, ".py")
	not endswith(path, ".tsv")
}

# On the added and edited sides the file exists, so the classification is its
# own first bytes rather than its path.
authored_shell(path) if {
	under_mise_tasks(path)
	some line in input.tree.lines[path]
	startswith(line, "#MISE description=")
}

authored_shell(path) if {
	under_mise_tasks(path)
	some line in input.tree.lines[path]
	startswith(line, "#!")
}

# The governed set on the head side.
governed_at_head(path) if authored_shell(path)

governed_at_head(path) if is_bats(path)

# The governed set on the deleted side, where there is nothing to read.
governed_when_deleted(path) if under_mise_tasks(path)

governed_when_deleted(path) if is_bats(path)

# ---------------------------------------------------------------------------
# A: a migration does not ADD an authored shell rule or a bats suite.
# ---------------------------------------------------------------------------

violation contains {
	"rule": "shell-rule-retired",
	"verdict": "V-SHELL-RULE-ADDED",
	"subjects": [{"path": path}],
} if {
	some path in delta.added
	governed_at_head(path)
}

# ---------------------------------------------------------------------------
# B: a migration does not EDIT one in place. The load-bearing arm.
# ---------------------------------------------------------------------------

violation contains {
	"rule": "shell-rule-retired",
	"verdict": "V-SHELL-RULE-EDITED",
	"subjects": [{"path": path}],
} if {
	some path in delta.edited
	governed_at_head(path)
	not only_drops_a_retired_reference(path)
}

# THE ONE ADMITTED EDIT, and it is what makes this campaign able to clean up
# after itself (CLOUD-1051).
#
# Retiring a program REQUIRES editing the siblings that declare it. The measured
# instance: `hooks-wiring-check.sh` carries a `DECLARED` table naming every
# by-path hook registration, and its own `wiring-declaration-stale` refuses a row
# whose subject no longer exists — so retiring `stop-guard.sh` forces a one-line
# deletion in a governed file, which this arm then refused. `V-SHELL-RULE-EDITED`
# declares no override route and no `bypass_env`, so the campaign was structurally
# unable to complete a retirement it had itself mandated.
#
# THE NARROWING IS EXACT AND NOT A JUDGEMENT: every line the base had and the head
# lacks must NAME A PATH THIS SAME DELTA DELETED. Removing a dead reference is
# admitted; removing anything else is not, and neither is adding a line. So this
# cannot become a licence to maintain a shell rule in place, which is the whole
# reason the arm above exists.
#
# COULD-NOT-LOOK REFUSES. `base-lines` omits a path whose base blob would not
# read, and an absent base side means the removed set is unknowable — so the
# admission does not hold and the edit is refused, which is the safe direction
# for an arm whose failure mode is a silent licence.
only_drops_a_retired_reference(path) if {
	base := delta["base-lines"][path]
	head := {line | some line in input.tree.lines[path]}
	removed := {line | some line in base; not line in head}

	# An edit that removed nothing is not this case: it added or reordered, and
	# neither is a retirement's cleanup.
	count(removed) > 0

	# Every removed line names a path this change retires.
	count({line |
		some line in removed
		some gone in delta.deleted
		contains(line, gone)
	}) == count(removed)

	# AND NOTHING WAS ADDED THAT IS NOT A TRUNCATION OF A REMOVED LINE. Without a
	# clause here a change could delete a program, drop its declaration row, and
	# smuggle an unrelated rewrite into the same file.
	#
	# The truncation half is not a loosening for convenience — it is the shape a
	# real declaration table produces, measured. It is also why
	# `hooks-wiring-check.sh` now opens its table on a line of its own with no
	# entry glued to it: with each row on its own line every row is independently
	# removable, and the next retirement in this campaign does not have to shorten
	# anything at all. Its consumers already skip an empty pattern, so the leading
	# blank costs nothing. `hooks-wiring-check.sh` opens its
	# table as `DECLARED="${HOOKS_WIRING_DECLARED-` and the FIRST entry used to sit
	# on that same line, so removing the first row rewrote the opening line rather
	# than deleting it. An added line that is a strict PREFIX of a removed one, with
	# the dropped remainder naming a path this delta deleted, is exactly that edit
	# and nothing else: it can only ever shorten, never introduce a byte the base
	# did not already carry at that position.
	added := {line | some line in input.tree.lines[path]; not line in {l | some l in base}}
	count({line | some line in added; truncates_a_retired_reference(line, removed)}) == count(added)
}

# An added line that is a strict prefix of a removed line, where everything the
# prefix drops names a path this same delta deleted.
#
# `startswith` plus the remainder test rather than a regex: the admission has to
# be that the added line INTRODUCES NOTHING, and a prefix relation is the only
# spelling of that which cannot be satisfied by a rewrite.
truncates_a_retired_reference(line, removed) if {
	some was in removed
	startswith(was, line)
	count(was) > count(line)
	some gone in delta.deleted
	contains(substring(was, count(line), -1), gone)
}

# ---------------------------------------------------------------------------
# C: a DELETION owes exactly one mapping, and that mapping owes two successors.
# ---------------------------------------------------------------------------

violation contains {
	"rule": "shell-rule-retired",
	"verdict": "V-RETIREMENT-UNMAPPED",
	"subjects": [{"path": path}],
} if {
	some path in delta.deleted
	governed_when_deleted(path)
	count(arms_for(path)) == 0
}

violation contains {
	"rule": "shell-rule-retired",
	"verdict": "V-RETIREMENT-AMBIGUOUS",
	"subjects": [{"path": path}],
} if {
	some path in delta.deleted
	governed_when_deleted(path)
	count(arms_for(path)) > 1
}

violation contains {
	"rule": "shell-rule-retired",
	"verdict": "V-SUCCESSOR-NO-SURFACE",
	"subjects": [{"path": path}],
} if {
	some path in delta.deleted
	governed_when_deleted(path)
	count(arms_for(path)) == 1
	not withdrawn_arm(path)
	not has_policy_surface(path)
}

violation contains {
	"rule": "shell-rule-retired",
	"verdict": "V-SUCCESSOR-NO-TEST",
	"subjects": [{"path": path}],
} if {
	some path in delta.deleted
	governed_when_deleted(path)
	count(arms_for(path)) == 1
	not withdrawn_arm(path)
	not has_binary_test(path)
}

# ---------------------------------------------------------------------------
# D: what the WITHDRAWAL arm owes instead (CLOUD-1080).
# ---------------------------------------------------------------------------

# THE CONDITION THAT KEEPS THIS NARROWER THAN A WAIVER. A withdrawal is honest only
# where the subject went with it; over a subject still standing this arm would be a
# blanket permission to delete governed files, which is the thing the module exists
# to refuse.
violation contains {
	"rule": "shell-rule-retired",
	"verdict": "V-WITHDRAWAL-SUBJECT-ALIVE",
	"subjects": [{"path": path}],
} if {
	some path in delta.deleted
	governed_when_deleted(path)
	count(arms_for(path)) == 1
	withdrawn_arm(path)
	count(withdrawn_subjects(path)) == 0
}

# It names no successor, so the reason is the only thing a reader can check the
# claim against. An arm with neither is a file deleted with a marker on it.
violation contains {
	"rule": "shell-rule-retired",
	"verdict": "V-WITHDRAWAL-UNEXPLAINED",
	"subjects": [{"path": path}],
} if {
	some path in delta.deleted
	governed_when_deleted(path)
	count(arms_for(path)) == 1
	withdrawn_arm(path)
	count(withdrawal_reason(path)) == 0
}

# ---------------------------------------------------------------------------
# The ledger, read out of the declared lines.
# ---------------------------------------------------------------------------

# The three arms, spelled here exactly as `[rule.conserves]` spells them. They
# are duplicated across two authorities and that is a known seam rather than an
# oversight: `rules-drift` holds this list to the TOML, so a rename that touched
# one and not the other is a finding rather than a silently dead predicate.
arm_markers := ["// carried:", "// subsumed:", "// changed:", "// withdrawn:"]

# THE FOURTH ARM IS THE ONE THAT NAMES NO SUCCESSOR (CLOUD-1080), and it is here
# for the same reason the other three are: this module reads `[rule.conserves]`'s
# declaration one level up, so an arm the case granularity accepts and the file
# granularity refuses would leave an honest deletion with no landable spelling at
# either level. `conserves` grew it first, over the cases; this is the file.
#
# A WITHDRAWAL IS NOT A MIGRATION. The three above answer "where did the predicate
# go", which is the right question for a port. It is the wrong question for a file
# deleted because the thing it governed should not exist: there is no successor, so
# demanding a policy surface and a compiled-binary test forces a mapping that names
# something which does not hold the predicate — the false `subsumed` in this
# module's vocabulary.
#
# So this arm trades those two obligations for two others, and it is strictly
# narrower than a `[[waiver]]` over the path, because it is spent one file at a
# time and only once the subject went with it.
withdrawn_arm(path) if {
	some row in arms_for(path)
	startswith(row, "// withdrawn:")
}

# THE SUBJECT IS NAMED ON THE ROW, and the reason it is named rather than read is
# a stated engine bound rather than a preference. `input.tree["base-delta"]`'s
# `base-lines` is bounded to EDITED paths by construction — `git.rs` says so on the
# field: *"not `added` (there is no base side), not `deleted` (the head side is
# gone)"*. A dying suite's own `# subject:` header therefore cannot be read from
# this surface at all, so the file granularity names what died where the CASE
# granularity reads it out of the base text the ratchet already buffers.
#
# WHAT THAT COSTS, stated rather than discovered: the subject here is
# author-declared, where `conserves`'s arm reads the dying file's own declaration.
# It is still not a free claim — the named path must appear in THIS delta's
# `deleted` set, so a withdrawal cannot be spelled without actually retiring
# something — but an author could name a different deleted path than the one the
# suite declared. Closing that needs the base side of a deleted path, which is an
# engine capability this row does not have and does not invent.
withdrawn_fields(path) := fields if {
	some row in arms_for(path)
	startswith(row, "// withdrawn:")
	all := split(trim_space(substring(row, count("// withdrawn:"), -1)), " ")
	fields := [word | some i, word in all; i > 0; word != ""]
}

# The fields naming a path this same change retired. At least one is owed: that is
# the whole narrowing, and it is what keeps the arm from being a `[[waiver]]` over
# the path with better manners.
withdrawn_subjects(path) := subjects if {
	subjects := {word |
		some word in withdrawn_fields(path)

		# NOT THE RETIRED PATH ITSELF. Without this the row could name the dying
		# file again and satisfy the narrowing with the very deletion it is
		# excusing — a withdrawal justified by its own subject.
		word != path
		some gone in delta.deleted
		word == gone
	}
}

# Everything else on the row is the reason. It names no successor, so this is the
# only thing a reader can check the claim against, and it is owed.
withdrawal_reason(path) := words if {
	subjects := withdrawn_subjects(path)
	words := {word |
		some word in withdrawn_fields(path)
		not word in subjects
	}
}

# Every ledger row naming `path`, as `<marker> <path> <successor>...`. A row is
# matched on the path being the FIRST field after the marker, so a successor path
# that happens to equal another retired file's name does not claim its mapping.
arms_for(path) := rows if {
	rows := {row |
		some file, lines in input.tree.lines
		startswith(file, "crates/batten/tests/")
		some line in lines
		some marker in arm_markers
		trimmed := trim_space(line)
		startswith(trimmed, marker)
		fields := split(trim_space(substring(trimmed, count(marker), -1)), " ")
		fields[0] == path
		row := trimmed
	}
}

# The successors named on `path`'s one arm, as the fields after the retired path.
successors_for(path) := names if {
	names := {name |
		some row in arms_for(path)
		some marker in arm_markers
		startswith(row, marker)
		fields := split(trim_space(substring(row, count(marker), -1)), " ")
		some i, name in fields
		i > 0
		name != ""
	}
}

has_policy_surface(path) if {
	some name in successors_for(path)
	startswith(name, "policy/")
	endswith(name, ".rego")
}

has_policy_surface(path) if {
	some name in successors_for(path)
	startswith(name, "crates/batten/src/")
	endswith(name, ".rs")
}

has_binary_test(path) if {
	some name in successors_for(path)
	startswith(name, "crates/batten/tests/")
	endswith(name, ".rs")
}

# NO `deny` RULE, deliberately. The engine reads both names, and they carry
# different shapes: `deny` is a set of bare STRINGS attributed to the enabling
# row, `violation` a set of objects carrying their own `rule` id. Publishing the
# objects below under `deny` too would put an object on the string channel, and
# every other module in this corpus declares `violation` alone for that reason.
#
# ---------------------------------------------------------------------------
# Load-time tier. These pin the predicate; `crates/batten/tests/shell_
# retirement.rs` is the tier that proves the ENGINE builds the shape they read.
# ---------------------------------------------------------------------------

test_added_shell_rule_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {"added": ["mise-tasks/new-gate.sh"], "edited": [], "deleted": []},
		"lines": {"mise-tasks/new-gate.sh": ["#!/usr/bin/env bash", "#MISE description=\"x\""]},
	}}
}

test_added_bats_suite_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {"added": ["tests/new-gate.bats"], "edited": [], "deleted": []},
		"lines": {},
	}}
}

test_edited_shell_rule_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {"added": [], "edited": ["mise-tasks/old-gate.sh"], "deleted": []},
		"lines": {"mise-tasks/old-gate.sh": ["#MISE description=\"x\""]},
	}}
}

# THE ADMITTED EDIT, and the three cases that keep it from becoming a licence.
# The retirement's own cleanup: the declaration row for a program this same
# change deletes comes out, and nothing else moves.
test_dropping_a_retired_reference_is_admitted if {
	count(violation) == 0 with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": ["mise-tasks/wiring.sh"],
			"deleted": ["mise-tasks/old-gate.sh"],
			"base-lines": {"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "mise-tasks/old-gate.sh CLOUD-312", "mise-tasks/other.sh CLOUD-312"]},
		},
		"lines": {
			"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "mise-tasks/other.sh CLOUD-312"],
			"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs"],
		},
	}}
}

# ANTI-VACUITY, and without it the arm above passes every edit that happens to
# accompany a deletion. The removed line names a path this change did NOT retire,
# so it is ordinary maintenance and is still refused.
test_dropping_a_line_naming_a_live_path_is_still_refused if {
	some v in violation with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": ["mise-tasks/wiring.sh"],
			"deleted": ["mise-tasks/old-gate.sh"],
			"base-lines": {"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "mise-tasks/still-here.sh CLOUD-312"]},
		},
		"lines": {
			"mise-tasks/wiring.sh": ["#!/usr/bin/env bash"],
			"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs"],
		},
	}}
	v.verdict == "V-SHELL-RULE-EDITED"
}

# AND AN ADDED LINE IS NOT CLEANUP. Without this conjunct a change could delete a
# program, drop its declaration row, and smuggle an unrelated rewrite through in
# the same file.
test_an_edit_that_also_adds_a_line_is_refused if {
	some v in violation with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": ["mise-tasks/wiring.sh"],
			"deleted": ["mise-tasks/old-gate.sh"],
			"base-lines": {"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "mise-tasks/old-gate.sh CLOUD-312"]},
		},
		"lines": {
			"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "echo something new"],
			"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs"],
		},
	}}
	v.verdict == "V-SHELL-RULE-EDITED"
}

# THE MEASURED SHAPE the truncation clause exists for. `hooks-wiring-check.sh`
# opened its `DECLARED` table with the first entry glued to the assignment, so
# removing that entry SHORTENED the opening line instead of deleting it. The
# added line introduces no byte the base did not carry, and everything it drops
# names a path this delta retired.
test_a_line_truncated_at_a_retired_reference_is_admitted if {
	count(violation) == 0 with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": ["mise-tasks/wiring.sh"],
			"deleted": ["mise-tasks/old-gate.sh"],
			"base-lines": {"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "DECLARED=\"${T-mise-tasks/old-gate.sh CLOUD-312", "mise-tasks/other.sh CLOUD-312"]},
		},
		"lines": {
			"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "DECLARED=\"${T-", "mise-tasks/other.sh CLOUD-312"],
			"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs"],
		},
	}}
}

# ANTI-VACUITY FOR THE TRUNCATION CLAUSE, and without it a prefix relation would
# admit any shortening at all. What this truncation drops names no retired path,
# so it is ordinary maintenance and is still refused.
test_a_truncation_dropping_a_live_reference_is_refused if {
	some v in violation with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": ["mise-tasks/wiring.sh"],
			"deleted": ["mise-tasks/old-gate.sh"],
			"base-lines": {"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "DECLARED=\"${T-mise-tasks/still-here.sh CLOUD-312", "mise-tasks/old-gate.sh CLOUD-312"]},
		},
		"lines": {
			"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "DECLARED=\"${T-"],
			"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs"],
		},
	}}
	v.verdict == "V-SHELL-RULE-EDITED"
}

# COULD NOT LOOK REFUSES. A base side this could not read leaves the removed set
# unknowable, and an arm whose failure mode is a silent licence must fail closed.
test_an_edit_with_no_readable_base_side_is_refused if {
	some v in violation with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": ["mise-tasks/wiring.sh"],
			"deleted": ["mise-tasks/old-gate.sh"],
			"base-lines": {},
		},
		"lines": {
			"mise-tasks/wiring.sh": ["#!/usr/bin/env bash"],
			"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs"],
		},
	}}
	v.verdict == "V-SHELL-RULE-EDITED"
}

test_deleted_and_fully_mapped_passes if {
	count(violation) == 0 with input as {"tree": {
		"base-delta": {"added": [], "edited": [], "deleted": ["mise-tasks/old-gate.sh"]},
		"lines": {"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs"]},
	}}
}

test_deleted_without_a_mapping_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {"added": [], "edited": [], "deleted": ["mise-tasks/old-gate.sh"]},
		"lines": {},
	}}
}

test_deleted_with_two_arms_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {"added": [], "edited": [], "deleted": ["mise-tasks/old-gate.sh"]},
		"lines": {"crates/batten/tests/old_gate.rs": [
			"// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs",
			"// subsumed: mise-tasks/old-gate.sh policy/other.rego crates/batten/tests/other.rs",
		]},
	}}
}

test_mapping_without_a_policy_surface_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {"added": [], "edited": [], "deleted": ["mise-tasks/old-gate.sh"]},
		"lines": {"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh crates/batten/tests/old_gate.rs"]},
	}}
}

test_mapping_without_a_binary_test_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {"added": [], "edited": [], "deleted": ["mise-tasks/old-gate.sh"]},
		"lines": {"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego"]},
	}}
}

# --- the fourth arm (CLOUD-1080) --------------------------------------------
#
# The positive case: the subject dies in the same delta, the row carries a reason,
# and NO successor is named. Under the three-arm module this exact input raised
# both `V-SUCCESSOR-NO-SURFACE` and `V-SUCCESSOR-NO-TEST`, which is the refusal the
# arm exists to remove.
test_a_withdrawal_whose_subject_died_is_admitted if {
	count(violation) == 0 with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": [],
			"deleted": ["tests/old-gate.bats", ".claude/old-wrapper.sh"],
		},
		"lines": {"crates/batten/tests/old_gate.rs": ["// withdrawn: tests/old-gate.bats .claude/old-wrapper.sh the feature should not exist"]},
	}}
}

# THE DISCRIMINATING CASE, and the reason this arm is narrower than a waiver over
# the path: the subject is left STANDING while its suite is deleted and claimed
# withdrawn. Without this condition the arm admits every deletion, and the positive
# case above would pass against a module that decided nothing.
test_a_withdrawal_over_a_live_subject_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": [],
			"deleted": ["tests/old-gate.bats"],
		},
		"lines": {"crates/batten/tests/old_gate.rs": ["// withdrawn: tests/old-gate.bats .claude/old-wrapper.sh the feature should not exist"]},
	}}
}

# A row naming NOTHING but a reason is refused too, and this is the case that keeps
# `withdrawn_subjects` from being satisfiable by prose: every word on the row is a
# reason word, none of them names a deleted path, so the arm claims a withdrawal
# without retiring anything.
test_a_withdrawal_naming_no_retired_path_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": [],
			"deleted": ["tests/old-gate.bats", ".claude/old-wrapper.sh"],
		},
		"lines": {"crates/batten/tests/old_gate.rs": ["// withdrawn: tests/old-gate.bats the feature should not exist"]},
	}}
}

# It names no successor, so the reason is the only checkable thing on the row.
test_a_withdrawal_with_no_reason_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": [],
			"deleted": ["tests/old-gate.bats", ".claude/old-wrapper.sh"],
		},
		"lines": {"crates/batten/tests/old_gate.rs": ["// withdrawn: tests/old-gate.bats .claude/old-wrapper.sh"]},
	}}
}

# The retired path itself is not its own subject. Without this a row could name the
# dying file again and satisfy the narrowing with the deletion it is excusing.
test_a_withdrawal_naming_only_itself_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {"added": [], "edited": [], "deleted": ["tests/old-gate.bats"]},
		"lines": {"crates/batten/tests/old_gate.rs": ["// withdrawn: tests/old-gate.bats tests/old-gate.bats a reason"]},
	}}
}

# The three successor-naming arms are untouched by the fourth: one of them over a
# row naming no policy surface still refuses, so the exemption is scoped to
# `withdrawn` rather than switched on for every deletion.
test_the_successor_obligation_still_binds_the_other_arms if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": [],
			"deleted": ["tests/old-gate.bats", ".claude/old-wrapper.sh"],
		},
		"lines": {"crates/batten/tests/old_gate.rs": ["// carried: tests/old-gate.bats crates/batten/tests/old_gate.rs"]},
	}}
}

# The anti-vacuity arm on the OTHER axis: an untouched tree, and a generated or
# non-shell path moving, must both be silent. Without this a module that refused
# everything would still pass every case above.
test_an_untouched_tree_is_silent if {
	count(violation) == 0 with input as {"tree": {
		"base-delta": {"added": [], "edited": [], "deleted": []},
		"lines": {},
	}}
}

test_a_non_shell_path_is_not_governed if {
	count(violation) == 0 with input as {"tree": {
		"base-delta": {
			"added": ["completions/batten.bash"],
			"edited": ["mise-tasks/replay-pointers.py", "crates/batten/src/lib.rs"],
			"deleted": ["mise-tasks/sbom-actions.tsv"],
		},
		"lines": {},
	}}
}

# A base that did not resolve is could-not-look: no findings, and deliberately
# not the same answer as a clean tree, because the engine emits `null` there and
# every predicate above is undefined rather than false.
test_an_unresolvable_base_reports_nothing if {
	count(violation) == 0 with input as {"tree": {"base-delta": null, "lines": {}}}
}
