# A migration that touches an authored shell rule retires it, or it does not land.
#
# CLOUD-1059, and it is a PREREQUISITE rather than a cleanup: CLOUD-843's campaign
# is retiring 144 shell programs and 161 bats suites onto the policy engine, and
# the failure that campaign cannot survive is a wave that EDITS a shell gate
# instead of replacing it. That reads as progress in every sensor the tree has —
# `bash-surface-not-growing` counts programs and an edit changes none, and
# `bats-tests-not-deleted` counts `@test` cases and an edit changes none — so the
# corpus stays exactly as large while the campaign reports movement.
#
# THE LEDGER IS CLOUD-908'S, NOT A SECOND MANIFEST. `[rule.conserves]` already
# declares the arms (`// carried:`, `// subsumed:`, `// changed:`) and already
# says where they live (`crates/batten/tests/*.rs`). This module reads that same
# declaration one level up: 908 conserves the CASES inside a dying suite, and this
# conserves the FILE. A second inventory of which shell programs exist is exactly
# the hand-maintained census CLOUD-929 measured going stale, so there is none.
#
# ─── WHAT A RETIREMENT ROW LOOKS LIKE ────────────────────────────────────────
#
#   // carried: mise-tasks/prose-only-check.sh policy/prose-only.rego crates/batten/tests/prose_only.rs
#
# The marker, the path that died, then its successors. Two obligations, because
# either alone is satisfiable by a port that does nothing: at least one successor
# must be a POLICY SURFACE (`policy/*.rego` or `crates/batten/src/*.rs`), and at
# least one must be a COMPILED-BINARY TEST (`crates/batten/tests/*.rs`). A port
# naming only a module has no evidence it works; a port naming only a test has
# nothing under test.
#
# ─── THE THREE REFUSALS, AND WHY EDIT IS THE LOAD-BEARING ONE ────────────────
#
# ADDED is the obvious one and the cheapest to satisfy honestly. EDITED is the one
# this module exists for: it is indistinguishable from ordinary maintenance to
# every other gate in the tree, and it is how a migration silently does not
# happen. DELETED-WITHOUT-A-MAPPING is CLOUD-908's shape at file granularity —
# the deletion is admitted, and nothing records what now holds the predicate.
#
# ─── WHAT THIS DOES NOT DECIDE, STATED RATHER THAN DISCOVERED ────────────────
#
# **A deleted path is classified BY PATH, never by its content.** It has no
# content at head — that is what deleted means — and reading the base tree to
# re-classify it would make the fact carry the bytes of a file the diff already
# says is gone. So `mise-tasks/**` minus the explicitly non-shell paths is the
# test on the deleted side, and a shebang/`#MISE description=` test on the added
# and edited sides where the lines exist. The asymmetry is deliberate and it errs
# toward DEMANDING a mapping, which is the safe direction: the cost of a wrong
# refusal is one ledger row, and the cost of a wrong pass is an unrecorded port.
#
# **Whether the successor actually holds the predicate is not decidable here.**
# That a named module exists and a named test exists is checkable; that the test
# discriminates is CLOUD-1020's question and `mutant`'s, and a gate over it would
# be the model verdict non-negotiable rule 3 forbids.
#
# **Generated artifacts are excluded by path and never judged.** Batten's own
# completions are derived output regenerated by `mise run completions`; treating
# one as an authored shell rule would refuse every change that regenerates them.
#
#MUTANT shell-added-unchecked|s@delta.added@[]@|an added authored shell rule is refused
#MUTANT shell-edited-unchecked|s@delta.edited@[]@|an edited-in-place shell rule is refused
#MUTANT shell-deletion-unmapped|s@count(arms_for(path)) == 1@true@|a deleted shell rule with no mapping is refused
#MUTANT shell-mapping-not-unique|s@count(arms_for(path)) == 1@count(arms_for(path)) > 0@|a deleted rule carrying two arms is refused
#MUTANT shell-successor-unproven|s@has_binary_test(path)@true@|a mapping naming no compiled-binary test is refused
#MUTANT shell-subject-alive-unchecked|s@not word in {gone | some gone in delta.deleted}@false@|CLOUD-1130 — a row naming a subject this delta does NOT retire is refused, whichever of the four markers it carries
# CLOUD-1121's arm. Dropping the exact-substitution test turns the repointing
# clause into a licence to rewrite any line that happens to accompany a deletion,
# which is what the three anti-vacuity cases above exist to catch.
#MUTANT repointing-not-exact|s@replace(was, gone, succ) == line@contains(was, gone)@|a repointing that also changes the line is refused
#
#MUTANT-EXEMPT CLOUD-931|no `tests/shell-retirement.bats` exists and none may: this row's whole subject is that a migration ships no new bats suite, so a suite named for it would be the thing it refuses. `mutant` resolves a gate's suite as `tests/$gate.bats`, so there is no named case a mutation could turn red. The second tier is `crates/batten/tests/shell_retirement.rs`, which drives the compiled binary and is the stronger evidence

# METADATA
# description: |
#   Bound to the TREE surface: `scope = "tree"`, so it reads the tree document
#   and never the mediated `{call, facts}` shape.
#   THE BRACKETS ARE NOT STYLE: the schema file carries a hyphen, so the dotted
#   form is a parse error reported as `invalid schema reference`.
#   THIS BLOCK IS YAML AND MUST STAY THE LAST COMMENT BLOCK BEFORE `package`.
# schemas:
#   - input: schema["policy-input.schema"]
package batten.shell_retirement

import rego.v1

rules contains "shell-rule-retired"

# ---------------------------------------------------------------------------
# The changed-file set, and the could-not-look channel.
# ---------------------------------------------------------------------------

# `input.tree.base-delta` is NULL when the base rev did not resolve, and `null`
# is not `undefined` — `not input.tree["base-delta"]` would be false for it, the
# exact slip CLOUD-701's review caught in `spawn-adapters`. So the delta is bound
# through a rule that holds only for an object, and every predicate below is
# undefined without it rather than vacuously clean.
delta := d if {
	d := input.tree["base-delta"]
	is_object(d)
}

# ---------------------------------------------------------------------------
# Which changed paths are the ones this row governs.
# ---------------------------------------------------------------------------

# A bats suite, on either side of the diff: the extension IS the declaration.
is_bats(path) if {
	startswith(path, "tests/")
	endswith(path, ".bats")
}

# Under `mise-tasks/`, excluding the paths that are not shell at all. Listed
# rather than pattern-matched because the set is small, closed, and a wrong
# guess here silently drops a program out of the campaign's scope.
under_mise_tasks(path) if {
	startswith(path, "mise-tasks/")
	not endswith(path, ".py")
	not endswith(path, ".tsv")
}

# On the added and edited sides the file exists, so the classification is its
# own first bytes rather than its path.
authored_shell(path) if {
	under_mise_tasks(path)
	some line in input.tree.lines[path]
	startswith(line, "#MISE description=")
}

authored_shell(path) if {
	under_mise_tasks(path)
	some line in input.tree.lines[path]
	startswith(line, "#!")
}

# The governed set on the head side.
governed_at_head(path) if authored_shell(path)

governed_at_head(path) if is_bats(path)

# The governed set on the deleted side, where there is nothing to read.
governed_when_deleted(path) if under_mise_tasks(path)

governed_when_deleted(path) if is_bats(path)

# ---------------------------------------------------------------------------
# A: a migration does not ADD an authored shell rule or a bats suite.
# ---------------------------------------------------------------------------

violation contains {
	"rule": "shell-rule-retired",
	"verdict": "V-SHELL-RULE-ADDED",
	"subjects": [{"path": path}],
} if {
	some path in delta.added
	governed_at_head(path)
}

# ---------------------------------------------------------------------------
# B: a migration does not EDIT one in place. The load-bearing arm.
# ---------------------------------------------------------------------------

violation contains {
	"rule": "shell-rule-retired",
	"verdict": "V-SHELL-RULE-EDITED",
	"subjects": [{"path": path}],
} if {
	some path in delta.edited
	governed_at_head(path)
	not only_drops_a_retired_reference(path)
}

# THE ONE ADMITTED EDIT, and it is what makes this campaign able to clean up
# after itself (CLOUD-1051).
#
# Retiring a program REQUIRES editing the siblings that declare it. The measured
# instance: `hooks-wiring-check.sh` carries a `DECLARED` table naming every
# by-path hook registration, and its own `wiring-declaration-stale` refuses a row
# whose subject no longer exists — so retiring `stop-guard.sh` forces a one-line
# deletion in a governed file, which this arm then refused. `V-SHELL-RULE-EDITED`
# declares no override route and no `bypass_env`, so the campaign was structurally
# unable to complete a retirement it had itself mandated.
#
# THE NARROWING IS EXACT AND NOT A JUDGEMENT: every line the base had and the head
# lacks must NAME A PATH THIS SAME DELTA DELETED. Removing a dead reference is
# admitted; removing anything else is not, and neither is adding a line. So this
# cannot become a licence to maintain a shell rule in place, which is the whole
# reason the arm above exists.
#
# COULD-NOT-LOOK REFUSES. `base-lines` omits a path whose base blob would not
# read, and an absent base side means the removed set is unknowable — so the
# admission does not hold and the edit is refused, which is the safe direction
# for an arm whose failure mode is a silent licence.
only_drops_a_retired_reference(path) if {
	base := delta["base-lines"][path]
	head := {line | some line in input.tree.lines[path]}
	removed := {line | some line in base; not line in head}

	# An edit that removed nothing is not this case: it added or reordered, and
	# neither is a retirement's cleanup.
	count(removed) > 0

	# Every removed line names a path this change retires.
	#
	# `mentions_retired` rather than a bare `contains` since CLOUD-1149: bash does
	# not spell a sibling as a repo-relative path, so `$(dirname "$0")/x.sh` named
	# nothing this clause could see and every such cleanup was refused.
	count({line |
		some line in removed
		some gone in delta.deleted
		mentions_retired(path, line, gone)
	}) == count(removed)

	# AND NOTHING WAS ADDED THAT IS NOT A TRUNCATION OF A REMOVED LINE. Without a
	# clause here a change could delete a program, drop its declaration row, and
	# smuggle an unrelated rewrite into the same file.
	#
	# The truncation half is not a loosening for convenience — it is the shape a
	# real declaration table produces, measured. It is also why
	# `hooks-wiring-check.sh` now opens its table on a line of its own with no
	# entry glued to it: with each row on its own line every row is independently
	# removable, and the next retirement in this campaign does not have to shorten
	# anything at all. Its consumers already skip an empty pattern, so the leading
	# blank costs nothing. `hooks-wiring-check.sh` opens its
	# table as `DECLARED="${HOOKS_WIRING_DECLARED-` and the FIRST entry used to sit
	# on that same line, so removing the first row rewrote the opening line rather
	# than deleting it. An added line that is a strict PREFIX of a removed one, with
	# the dropped remainder naming a path this delta deleted, is exactly that edit
	# and nothing else: it can only ever shorten, never introduce a byte the base
	# did not already carry at that position.
	added := {line | some line in input.tree.lines[path]; not line in {l | some l in base}}
	count({line |
		some line in added
		admitted_addition(path, line, removed)
	}) == count(added)
}

# An added line is admitted three ways, and all three are shapes rather than
# judgements.
admitted_addition(_, line, removed) if truncates_a_retired_reference(line, removed)

admitted_addition(_, line, removed) if repoints_at_the_declared_successor(line, removed)

admitted_addition(path, line, removed) if repoints_at_the_declared_invocation(path, line, removed)

admitted_addition(_, line, removed) if drops_a_retired_name(line, removed)

# ---------------------------------------------------------------------------
# How a caller SPELLS the program it is losing (CLOUD-1149).
# ---------------------------------------------------------------------------

# The last segment of a repo-relative path.
#
# COMPUTED FROM `gone`, never written: an editor cannot widen the match by naming
# some other basename here, because the only basename this reaches is the one a
# path in `delta.deleted` already has.
basename(path) := name if {
	parts := split(path, "/")
	name := parts[count(parts) - 1]
}

# The extensionless form of a basename: `graph-check.sh` -> `graph-check`.
#
# COMPUTED FROM `gone` like `basename`, never written, so the only stem this
# reaches is one a path in `delta.deleted` already has.
stem(name) := head if {
	parts := split(name, ".")
	count(parts) > 1
	head := concat(".", array.slice(parts, 0, count(parts) - 1))
}

# Every way this delta's dying path can be NAMED in a list: the path, its
# basename, and its basename without the extension.
#
# The third is the one `board-sweep.sh` needs. Its loop names TASKS and the files
# carry `.sh` (CLOUD-865), so the line reads `for gate in graph-check …` and the
# token is the stem rather than any filename.
naming_forms(gone) := forms if {
	base := basename(gone)
	forms := {gone, base} | {s | s := stem(base)}
}

# A RETIRED NAME DROPPED FROM A LIST (CLOUD-1224).
#
# The fourth admitted addition, and the one that reaches a caller which never
# names its callee as a path at all. `mise-tasks/board-sweep.sh:229` is:
#
#     for gate in graph-check duplicate-close-check released in-progress-drain …
#
# Retiring one of those gates edits that line, and none of the three arms above
# can see it: nothing is shortened, the line carries no repo-relative path for
# `contains` to find, and there is no successor being pointed at — the honest
# edit is that a name goes away and nothing replaces it.
#
# THE SPAN IS DERIVED AND THE JOIN IS EXACT, which is what keeps this from being
# a licence to edit a list. The removed line is split at the name's own
# occurrence, and the added line must equal the two halves concatenated BYTE FOR
# BYTE — so a change that also touched anything else on the line is refused,
# and nothing can be introduced. Taking one adjacent space with the name is the
# only latitude, because dropping `foo ` from `a foo b` is how a list actually
# reads afterwards.
#
# AND THE NAME MUST BE ONE THIS DELTA DELETES, through `naming_forms`, which
# computes every form from `gone` rather than accepting one. So a list entry can
# only be dropped by the change that retires the thing it names.
drops_a_retired_name(line, removed) if {
	some was in removed
	some gone in delta.deleted
	some form in naming_forms(gone)
	some span in {concat("", [form, " "]), concat("", [" ", form]), form}
	at := indexof(was, span)
	at >= 0
	before := substring(was, 0, at)
	after := substring(was, at + count(span), -1)
	line == concat("", [before, after])
}

# The spellings of one piece of text: itself, and itself with one MATCHED pair of
# double quotes removed.
#
# A set rather than a function, so an unbalanced quote is simply not a second
# spelling rather than an error. `"$here/x.sh"` and `$here/x.sh` are the same
# reference; a lone `"` is part of the text.
spellings(text) := forms if {
	inner := {stripped |
		startswith(text, "\"")
		endswith(text, "\"")
		count(text) > 1
		stripped := substring(text, 1, count(text) - 2)
	}
	forms := {text} | inner
}

# The variable a line assigns, or nothing.
#
# `indexof` plus a NAME TEST rather than a capture: `regex.match` takes a whole
# pattern from the registry, and a submatch would need a format string — which is
# an inline regex under another name and is refused at load.
assigned_name(line) := name if {
	at := indexof(line, "=")
	at > 0
	name := trim_space(substring(line, 0, at))
	regex.match(data.batten.patterns["shell-identifier"], name)
}

assigned_value(line) := value if {
	at := indexof(line, "=")
	at > 0
	value := trim_space(substring(line, at + 1, -1))
}

# A variable this file's BASE text binds to its own script directory.
#
# The two-step form is the spelling this tree's real callers use — `board-sweep`
# computes `here` once and spends it many lines later — and no single-line
# predicate can see it.
#
# THE BASE SIDE AND NEVER THE HEAD. The binding being read is the one the caller
# had BEFORE the edit, which is the only side on which the dying path is still
# resolvable. Reading the head would let an edit introduce the very binding it
# then claims to be following.
script_dir_vars(path) := names if {
	names := {variable |
		some line in delta["base-lines"][path]
		variable := assigned_name(line)
		some form in spellings(assigned_value(line))
		regex.match(data.batten.patterns["shell-script-directory"], form)
	}
}

# A variable this file's BASE text binds to the WHOLE retired path.
#
# The shape `graph-check.sh` uses: the callee is resolved once into `lint` and
# spent as `"$lint"` a hundred lines later. Without this the ARITY of the call
# cannot change, and every real repointing onto a verb changes it — a path is one
# word and `mise run x` is three.
retired_path_vars(path, gone) := names if {
	names := {variable |
		some line in delta["base-lines"][path]
		variable := assigned_name(line)
		some form in spellings(assigned_value(line))
		is_retired_reference_by_text(path, form, gone)
	}
}

# ARM 1 — the literal repo-relative path. What a workflow step, a declaration
# table row or a comment carries, and the only arm this module has ever had.
is_retired_reference_by_text(_, form, gone) if form == gone

# ARM 2 — the constructed sibling written on one line. The span ENDS in
# `/<basename>` and everything before it is a script-directory expression, tested
# against a pattern anchored at both ends.
is_retired_reference_by_text(_, form, gone) if {
	tail := concat("", ["/", basename(gone)])
	endswith(form, tail)
	head := substring(form, 0, count(form) - count(tail))
	regex.match(data.batten.patterns["shell-script-directory"], head)
}

# ARM 3 — the directory in a variable, the name on the line: `"$here/x.sh"`.
is_retired_reference_by_text(path, form, gone) if {
	some variable in script_dir_vars(path)
	some spelling in {concat("", ["$", variable]), concat("", ["${", variable, "}"])}
	form == concat("", [spelling, "/", basename(gone)])
}

# THE FULL SPAN TEST: arms 1-3, plus ARM 4 — the whole path already in a
# variable, `"$lint"`.
#
# Split from the three above so the definition is a DAG: `retired_path_vars`
# reads arms 1-3, and this reads `retired_path_vars`.
is_retired_reference(path, span, gone) if {
	some form in spellings(span)
	is_retired_reference_by_text(path, form, gone)
}

is_retired_reference(path, span, gone) if {
	some form in spellings(span)
	some variable in retired_path_vars(path, gone)
	form in {concat("", ["$", variable]), concat("", ["${", variable, "}"])}
}

# DOES THIS WHOLE LINE NAME A PATH THIS DELTA RETIRES? The removal clause's
# question, and it is deliberately looser than the span test above: a removed
# line is going away whole, so nothing on it has to be byte-checked. Nothing is
# being introduced, so `contains` is honest here where on the addition side it
# would be a licence.
mentions_retired(_, line, gone) if contains(line, gone)

# THE MARKER RATHER THAN THE EXPRESSION, for the reason `sibling-resolves` gives
# about its own `script_dir_line`: the spelling varies more than one regex should
# try to hold. Two conjuncts — the basename is present AND the line resolves THIS
# script's directory — is what tells `$(dirname "$0")/x.sh` from
# `"$REPO_ROOT/tools/x.sh"`, which names somebody else's tree.
mentions_retired(_, line, gone) if {
	contains(line, concat("", ["/", basename(gone)]))
	regex.match(data.batten.patterns["shell-script-directory-marker"], line)
}

mentions_retired(path, line, gone) if {
	some variable in script_dir_vars(path)
	contains(line, concat("", ["$", variable, "/", basename(gone)]))
}

mentions_retired(path, line, gone) if {
	some variable in retired_path_vars(path, gone)
	some spelling in {concat("", ["$", variable]), concat("", ["${", variable, "}"])}
	contains(line, spelling)
}

# AND THE BARE NAME, for the list shape `drops_a_retired_name` admits
# (CLOUD-1224). `board-sweep.sh` names TASKS and builds the filename, so the
# removed line carries `old-gate` and no path at all — every arm above looks for
# a path or a variable holding one, and none of them can see it.
#
# LOOSER THAN THE ARMS ABOVE, and safe for the same reason they are: this decides
# a line that is GOING AWAY, so nothing on it has to be byte-checked. What is
# introduced is checked by `drops_a_retired_name`, which requires the added line
# to equal this one minus that exact name. The pair is tight even though neither
# half is.
mentions_retired(_, line, gone) if {
	some form in naming_forms(gone)
	contains(line, form)
}

# A REPOINTING: the removed line with the retired path replaced by a successor
# its own ledger row declares, and nothing else changed (CLOUD-1121).
#
# THE CAMPAIGN COULD NOT COMPLETE A RETIREMENT IT HAD ITSELF MANDATED without
# this, which is the same defect CLOUD-1051's truncation clause was added for, one
# case further on. Retiring a program requires editing the siblings that CALL it,
# and a caller does not merely drop a line: it names the successor instead. The
# truncation clause admits only shortening, so every such retirement was refused
# with no landable spelling — `V-SHELL-RULE-EDITED` declares no override route and
# no `bypass_env`.
#
# THIS CLAUSE ALONE DOES NOT REACH `mise-tasks/graph-check.sh`, AND SAYING IT DID
# WAS THIS COMMENT'S OWN DEFECT (CLOUD-1149). It used to close "measured on
# `mise-tasks/graph-check.sh`, whose one line resolves the readiness gate by
# path" — and that line is `lint="$(dirname "$0")/ready-lint.sh"`, which contains
# no repo-relative path, so `contains(was, gone)` is false and this clause never
# fires on it. Comment and code disagreed, and the comment was the half a reader
# consults to decide whether a retirement is landable. Measured across the tree:
# 41 relative-resolution call sites in 27 governed callers, none of them reachable
# here.
#
# `mentions_retired` and `repoints_at_the_declared_invocation` below are what
# actually reach that shape. This clause is the LITERAL-PATH one, and it is still
# the whole of what a workflow step or a declaration table needs.
#
# IT IS NOT A LICENCE, and the narrowing is what makes that structural rather than
# hoped. The substitution is EXACT — `replace(was, gone, succ)` must equal the
# added line byte for byte — so nothing else on the line may move. `gone` must be a
# path THIS DELTA deleted, so a repointing cannot be spelled without actually
# retiring something. And `succ` must come from `successors_for(gone)`, which reads
# the retired path's own `// carried:` row: the successor is the one the ledger
# already committed to, never a target the editor picks here. A caller cannot
# therefore be repointed at anything the retirement did not declare.
repoints_at_the_declared_successor(line, removed) if {
	some was in removed
	some gone in delta.deleted
	contains(was, gone)
	some succ in path_successors_for(gone)
	replace(was, gone, succ) == line
}

# A REPOINTING AT A DECLARED INVOCATION (CLOUD-1219).
#
# The clause above substitutes one PATH for another, which is right for a caller
# that names its callee by path and will name the replacement by path — a
# workflow step, a declaration table row. It is the wrong shape for a SHELL
# caller of a program that retired onto a verb. `path_successors_for` yields file
# paths, so the substitution it admits is
# `lint="$(dirname "$0")/crates/batten/src/ready.rs"` — byte-checkable, and
# nonsense. The clause could be spelled and never usefully, which is the same
# failure one level down from the one CLOUD-1121 fixed.
#
# WHAT MAKES THIS NOT A LICENCE, and it is three separate narrowings:
#
#   * THE SPAN IS DERIVED, NEVER DECLARED. The successor occurs in the ADDED
#     line; the prefix before it and the suffix after it are read off that
#     occurrence, and the removed line must carry the same prefix and the same
#     suffix. The replaced span is therefore whatever the two lines disagree
#     about — never anything an editor names. That is `replace(…) == line`'s
#     exactness restated for a span the retired path's own spelling cannot
#     locate.
#   * THE SPAN MUST BE A REFERENCE TO A PATH THIS DELTA DELETED. Without this one
#     conjunct the decomposition admits replacing ANY single contiguous span of
#     ANY line that accompanies a deletion, which is the whole gate switched off.
#     `is_retired_reference` is that test, and it is a shape rather than a
#     judgement.
#   * THE TARGET COMES FROM THE LEDGER. `invocations_for(gone)` reads the retired
#     path's own arm, so a caller cannot be repointed at a command the retirement
#     did not commit to — the property CLOUD-1121 states, preserved verbatim one
#     field over.
repoints_at_the_declared_invocation(path, line, removed) if {
	some was in removed
	some gone in delta.deleted
	some succ in invocations_for(gone)

	at := indexof(line, succ)
	at >= 0
	before := substring(line, 0, at)
	after := substring(line, at + count(succ), -1)

	startswith(was, before)
	endswith(was, after)
	count(was) >= count(before) + count(after)
	span := substring(was, count(before), (count(was) - count(before)) - count(after))
	span != ""

	is_retired_reference(path, span, gone)
}

# An added line that is a strict prefix of a removed line, where everything the
# prefix drops names a path this same delta deleted.
#
# `startswith` plus the remainder test rather than a regex: the admission has to
# be that the added line INTRODUCES NOTHING, and a prefix relation is the only
# spelling of that which cannot be satisfied by a rewrite.
truncates_a_retired_reference(line, removed) if {
	some was in removed
	startswith(was, line)
	count(was) > count(line)
	some gone in delta.deleted
	contains(substring(was, count(line), -1), gone)
}

# ---------------------------------------------------------------------------
# C: a DELETION owes exactly one mapping, and that mapping owes two successors.
# ---------------------------------------------------------------------------

violation contains {
	"rule": "shell-rule-retired",
	"verdict": "V-RETIREMENT-UNMAPPED",
	"subjects": [{"path": path}],
} if {
	some path in delta.deleted
	governed_when_deleted(path)
	count(arms_for(path)) == 0
}

violation contains {
	"rule": "shell-rule-retired",
	"verdict": "V-RETIREMENT-AMBIGUOUS",
	"subjects": [{"path": path}],
} if {
	some path in delta.deleted
	governed_when_deleted(path)
	count(arms_for(path)) > 1
}

violation contains {
	"rule": "shell-rule-retired",
	"verdict": "V-SUCCESSOR-NO-SURFACE",
	"subjects": [{"path": path}],
} if {
	some path in delta.deleted
	governed_when_deleted(path)
	count(arms_for(path)) == 1
	not withdrawn_arm(path)
	not has_policy_surface(path)
}

violation contains {
	"rule": "shell-rule-retired",
	"verdict": "V-SUCCESSOR-NO-TEST",
	"subjects": [{"path": path}],
} if {
	some path in delta.deleted
	governed_when_deleted(path)
	count(arms_for(path)) == 1
	not withdrawn_arm(path)
	not has_binary_test(path)
}

# ---------------------------------------------------------------------------
# D: what the WITHDRAWAL arm owes instead (CLOUD-1080).
# ---------------------------------------------------------------------------

# THE CONDITION THAT KEEPS THIS NARROWER THAN A WAIVER. A withdrawal is honest only
# where the subject went with it; over a subject still standing this arm would be a
# blanket permission to delete governed files, which is the thing the module exists
# to refuse.
violation contains {
	"rule": "shell-rule-retired",
	"verdict": "V-WITHDRAWAL-SUBJECT-ALIVE",
	"subjects": [{"path": path}],
} if {
	some path in delta.deleted
	governed_when_deleted(path)
	count(arms_for(path)) == 1
	withdrawn_arm(path)
	count(withdrawn_subjects(path)) == 0
}

# AND THE CONDITION IS NOT THE WITHDRAWAL'S ALONE (CLOUD-1130). Guarded behind
# `withdrawn_arm` it could never fire for `carried`, `subsumed` or `changed`, so a
# row naming its own live subject was refused under one marker and admitted under
# the other three — the same claim, decided by which word the author typed.
#
# WHAT THIS ARM CAN SEE, AND THE BOUND ON IT. A dying suite's own `# subject:`
# header is unreadable from this surface: `base-lines` is bounded to EDITED paths
# by construction, and `line_sources` does not carry `tests/**/*.bats` at head
# either, so the only channel through which a subject reaches this module is the
# ledger row. Where the row names one, this decides it; where the row names none,
# `retirement_blockers` in `crates/batten/src/rules.rs` is the authority — it reads
# the declared header out of the base text the ratchet already buffers, and it is
# where CLOUD-1130's exploit is actually closed. Two authorities, one question,
# stated rather than left for a reader to discover the seam.
#
# GOVERNED PATHS ONLY, which is what keeps it off the successors. A `carried` row's
# tail is `policy/*.rego` and `crates/batten/tests/*.rs`, and neither is governed —
# so naming a successor can never trip this, and naming a shell program or a bats
# suite that this delta does not retire always does.
violation contains {
	"rule": "shell-rule-retired",
	"verdict": "V-RETIREMENT-SUBJECT-ALIVE",
	"subjects": [{"path": path}, {"path": subject}],
} if {
	some path in delta.deleted
	governed_when_deleted(path)
	count(arms_for(path)) == 1
	some subject in named_and_alive(path)
}

# The governed paths an arm names that this delta does NOT retire.
#
# `word != path` for `withdrawn_subjects`'s reason, one direction over: a row
# naming the dying file again would otherwise report the file being retired as its
# own surviving subject.
#
# ONLY THE TWO PROSE-FREE ARMS ARE READ, and that bound is the whole of what makes
# governed-ness a sound discriminator here. `carried` and `subsumed` spell a tail
# of paths and nothing else — a subject, then the surface and the test — so a
# governed word in one is a claimed subject by construction. The other two do not
# have that property:
#
#   * `// changed:` carries a free-text REASON after its successors, and a reason
#     is prose. "changed: tests/x.bats policy/x.rego crates/batten/tests/x.rs the
#     old mise-tasks/x.sh behaviour was wrong" names a governed path in a sentence,
#     not as a subject — and reading it as one refuses a conforming retirement.
#     Nothing positional separates the two, because the subject field is optional.
#   * `// withdrawn:` is subjects-and-reason with no successors at all, and
#     `V-WITHDRAWAL-SUBJECT-ALIVE` above already decides subject survival for it
#     through `withdrawn_subjects`. Reading it here too would be a second
#     authority over one question, answering from a weaker reading.
#
# WHAT THAT LEAVES OPEN, said rather than left for a reader to find: a `changed`
# row naming a live subject is not caught HERE. It is caught where CLOUD-1130 is
# actually closed — `retirement_blockers` in `crates/batten/src/rules.rs` reads the
# dying file's own declared `# subject:` header out of the base text and applies
# the same condition under every marker. This arm is the module's half over what
# the ROW declares; that one is the authority over what the FILE declared. Under-
# denying here is the sanctioned direction, and a false refusal in a `deny` gate
# the whole retirement campaign passes through is not.
named_and_alive(path) := subjects if {
	subjects := {word |
		some row in arms_for(path)
		some marker in ["// carried:", "// subsumed:"]
		startswith(row, marker)
		fields := split(trim_space(substring(row, count(marker), -1)), " ")
		some i, word in fields
		i > 0
		word != ""
		word != path
		governed_when_deleted(word)
		not word in {gone | some gone in delta.deleted}
	}
}

# It names no successor, so the reason is the only thing a reader can check the
# claim against. An arm with neither is a file deleted with a marker on it.
violation contains {
	"rule": "shell-rule-retired",
	"verdict": "V-WITHDRAWAL-UNEXPLAINED",
	"subjects": [{"path": path}],
} if {
	some path in delta.deleted
	governed_when_deleted(path)
	count(arms_for(path)) == 1
	withdrawn_arm(path)
	count(withdrawal_reason(path)) == 0
}

# ---------------------------------------------------------------------------
# The ledger, read out of the declared lines.
# ---------------------------------------------------------------------------

# The three arms, spelled here exactly as `[rule.conserves]` spells them. They
# are duplicated across two authorities and that is a known seam rather than an
# oversight: `rules-drift` holds this list to the TOML, so a rename that touched
# one and not the other is a finding rather than a silently dead predicate.
arm_markers := ["// carried:", "// subsumed:", "// changed:", "// withdrawn:"]

# THE FOURTH ARM IS THE ONE THAT NAMES NO SUCCESSOR (CLOUD-1080), and it is here
# for the same reason the other three are: this module reads `[rule.conserves]`'s
# declaration one level up, so an arm the case granularity accepts and the file
# granularity refuses would leave an honest deletion with no landable spelling at
# either level. `conserves` grew it first, over the cases; this is the file.
#
# A WITHDRAWAL IS NOT A MIGRATION. The three above answer "where did the predicate
# go", which is the right question for a port. It is the wrong question for a file
# deleted because the thing it governed should not exist: there is no successor, so
# demanding a policy surface and a compiled-binary test forces a mapping that names
# something which does not hold the predicate — the false `subsumed` in this
# module's vocabulary.
#
# So this arm trades those two obligations for two others, and it is strictly
# narrower than a `[[waiver]]` over the path, because it is spent one file at a
# time and only once the subject went with it.
withdrawn_arm(path) if {
	some row in arms_for(path)
	startswith(row, "// withdrawn:")
}

# THE SUBJECT IS NAMED ON THE ROW, and the reason it is named rather than read is
# a stated engine bound rather than a preference. `input.tree["base-delta"]`'s
# `base-lines` is bounded to EDITED paths by construction — `git.rs` says so on the
# field: *"not `added` (there is no base side), not `deleted` (the head side is
# gone)"*. A dying suite's own `# subject:` header therefore cannot be read from
# this surface at all, so the file granularity names what died where the CASE
# granularity reads it out of the base text the ratchet already buffers.
#
# WHAT THAT COSTS, stated rather than discovered: the subject here is
# author-declared, where `conserves`'s arm reads the dying file's own declaration.
# It is still not a free claim — the named path must appear in THIS delta's
# `deleted` set, so a withdrawal cannot be spelled without actually retiring
# something — but an author could name a different deleted path than the one the
# suite declared. Closing that needs the base side of a deleted path, which is an
# engine capability this row does not have and does not invent.
withdrawn_fields(path) := fields if {
	some row in arms_for(path)
	startswith(row, "// withdrawn:")
	all := split(trim_space(substring(row, count("// withdrawn:"), -1)), " ")
	fields := [word | some i, word in all; i > 0; word != ""]
}

# The fields naming a path this same change retired. At least one is owed: that is
# the whole narrowing, and it is what keeps the arm from being a `[[waiver]]` over
# the path with better manners.
withdrawn_subjects(path) := subjects if {
	subjects := {word |
		some word in withdrawn_fields(path)

		# NOT THE RETIRED PATH ITSELF. Without this the row could name the dying
		# file again and satisfy the narrowing with the very deletion it is
		# excusing — a withdrawal justified by its own subject.
		word != path
		some gone in delta.deleted
		word == gone
	}
}

# Everything else on the row is the reason. It names no successor, so this is the
# only thing a reader can check the claim against, and it is owed.
withdrawal_reason(path) := words if {
	subjects := withdrawn_subjects(path)
	words := {word |
		some word in withdrawn_fields(path)

		# THE RETIRED PATH IS NOT PROSE EITHER. `withdrawn_subjects` excludes it so
		# a row cannot be its own subject, and without the same exclusion here that
		# rejected word fell through into the reason set — so naming the dying file
		# twice satisfied both halves with no reason written at all.
		word != path
		not word in subjects
	}
}

# Every ledger row naming `path`, as `<marker> <path> <successor>...`. A row is
# matched on the path being the FIRST field after the marker, so a successor path
# that happens to equal another retired file's name does not claim its mapping.
arms_for(path) := rows if {
	rows := {row |
		some file, lines in input.tree.lines
		startswith(file, "crates/batten/tests/")
		some line in lines
		some marker in arm_markers
		trimmed := trim_space(line)
		startswith(trimmed, marker)
		fields := split(trim_space(substring(trimmed, count(marker), -1)), " ")
		fields[0] == path
		row := trimmed
	}
}

# The successors named on `path`'s one arm, as the fields after the retired path.
successors_for(path) := names if {
	names := {name |
		some row in arms_for(path)
		some marker in arm_markers
		startswith(row, marker)
		fields := split(trim_space(substring(row, count(marker), -1)), " ")
		some i, name in fields
		i > 0
		name != ""
	}
}

# The INVOCATION a retired path's arm declares, decoded from its one field
# (CLOUD-1219).
#
# ONE FIELD, BECAUSE THE ROW IS SPACE-SEPARATED. `successors_for` splits on " ",
# so an invocation written as three bare words arrives as three successors — and
# each would then be a target `repoints_at_the_declared_successor` could
# substitute for a PATH. The field carries its spaces as `+`, which no verb path,
# no task name and no tracked path in this tree contains, and this puts them back.
invocations_for(path) := commands if {
	commands := {command |
		some field in successors_for(path)
		regex.match(data.batten.patterns["retirement-invocation-field"], field)
		command := replace(substring(field, count("runs:"), -1), "+", " ")
	}
}

# The successors that are PATHS, which is what the two successor obligations and
# the path-repointing clause are about.
#
# SPLIT OUT WHEN THE INVOCATION FIELD ARRIVED, and the split is the whole of what
# keeps that field ADDITIVE: a `runs:` token can never satisfy
# `has_policy_surface`, can never satisfy `has_binary_test`, and can never be
# substituted in where a path belongs. A retirement still owes a policy surface
# and a compiled-binary test exactly as it did before the field existed.
path_successors_for(path) := names if {
	names := {name |
		some name in successors_for(path)
		not regex.match(data.batten.patterns["retirement-invocation-field"], name)
	}
}

has_policy_surface(path) if {
	some name in path_successors_for(path)
	startswith(name, "policy/")
	endswith(name, ".rego")
}

has_policy_surface(path) if {
	some name in path_successors_for(path)
	startswith(name, "crates/batten/src/")
	endswith(name, ".rs")
}

has_binary_test(path) if {
	some name in path_successors_for(path)
	startswith(name, "crates/batten/tests/")
	endswith(name, ".rs")
}

# NO `deny` RULE, deliberately. The engine reads both names, and they carry
# different shapes: `deny` is a set of bare STRINGS attributed to the enabling
# row, `violation` a set of objects carrying their own `rule` id. Publishing the
# objects below under `deny` too would put an object on the string channel, and
# every other module in this corpus declares `violation` alone for that reason.
#
# ---------------------------------------------------------------------------
# Load-time tier. These pin the predicate; `crates/batten/tests/shell_
# retirement.rs` is the tier that proves the ENGINE builds the shape they read.
# ---------------------------------------------------------------------------

test_added_shell_rule_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {"added": ["mise-tasks/new-gate.sh"], "edited": [], "deleted": []},
		"lines": {"mise-tasks/new-gate.sh": ["#!/usr/bin/env bash", "#MISE description=\"x\""]},
	}}
}

test_added_bats_suite_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {"added": ["tests/new-gate.bats"], "edited": [], "deleted": []},
		"lines": {},
	}}
}

test_edited_shell_rule_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {"added": [], "edited": ["mise-tasks/old-gate.sh"], "deleted": []},
		"lines": {"mise-tasks/old-gate.sh": ["#MISE description=\"x\""]},
	}}
}

# THE ADMITTED EDIT, and the three cases that keep it from becoming a licence.
# The retirement's own cleanup: the declaration row for a program this same
# change deletes comes out, and nothing else moves.
test_dropping_a_retired_reference_is_admitted if {
	count(violation) == 0 with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": ["mise-tasks/wiring.sh"],
			"deleted": ["mise-tasks/old-gate.sh"],
			"base-lines": {"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "mise-tasks/old-gate.sh CLOUD-312", "mise-tasks/other.sh CLOUD-312"]},
		},
		"lines": {
			"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "mise-tasks/other.sh CLOUD-312"],
			"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs"],
		},
	}}
}

# ANTI-VACUITY, and without it the arm above passes every edit that happens to
# accompany a deletion. The removed line names a path this change did NOT retire,
# so it is ordinary maintenance and is still refused.
test_dropping_a_line_naming_a_live_path_is_still_refused if {
	some v in violation with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": ["mise-tasks/wiring.sh"],
			"deleted": ["mise-tasks/old-gate.sh"],
			"base-lines": {"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "mise-tasks/still-here.sh CLOUD-312"]},
		},
		"lines": {
			"mise-tasks/wiring.sh": ["#!/usr/bin/env bash"],
			"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs"],
		},
	}}
	v.verdict == "V-SHELL-RULE-EDITED"
}

# AND AN ADDED LINE IS NOT CLEANUP. Without this conjunct a change could delete a
# program, drop its declaration row, and smuggle an unrelated rewrite through in
# the same file.
test_an_edit_that_also_adds_a_line_is_refused if {
	some v in violation with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": ["mise-tasks/wiring.sh"],
			"deleted": ["mise-tasks/old-gate.sh"],
			"base-lines": {"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "mise-tasks/old-gate.sh CLOUD-312"]},
		},
		"lines": {
			"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "echo something new"],
			"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs"],
		},
	}}
	v.verdict == "V-SHELL-RULE-EDITED"
}

# THE MEASURED SHAPE the truncation clause exists for. `hooks-wiring-check.sh`
# opened its `DECLARED` table with the first entry glued to the assignment, so
# removing that entry SHORTENED the opening line instead of deleting it. The
# added line introduces no byte the base did not carry, and everything it drops
# names a path this delta retired.
test_a_line_truncated_at_a_retired_reference_is_admitted if {
	count(violation) == 0 with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": ["mise-tasks/wiring.sh"],
			"deleted": ["mise-tasks/old-gate.sh"],
			"base-lines": {"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "DECLARED=\"${T-mise-tasks/old-gate.sh CLOUD-312", "mise-tasks/other.sh CLOUD-312"]},
		},
		"lines": {
			"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "DECLARED=\"${T-", "mise-tasks/other.sh CLOUD-312"],
			"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs"],
		},
	}}
}

# ANTI-VACUITY FOR THE TRUNCATION CLAUSE, and without it a prefix relation would
# admit any shortening at all. What this truncation drops names no retired path,
# so it is ordinary maintenance and is still refused.
test_a_truncation_dropping_a_live_reference_is_refused if {
	some v in violation with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": ["mise-tasks/wiring.sh"],
			"deleted": ["mise-tasks/old-gate.sh"],
			"base-lines": {"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "DECLARED=\"${T-mise-tasks/still-here.sh CLOUD-312", "mise-tasks/old-gate.sh CLOUD-312"]},
		},
		"lines": {
			"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "DECLARED=\"${T-"],
			"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs"],
		},
	}}
	v.verdict == "V-SHELL-RULE-EDITED"
}

# THE REPOINTING, and the three cases that keep it from becoming a licence
# (CLOUD-1121). The caller names the successor its ledger row declares, and
# nothing else on the line moves.
test_repointing_a_caller_at_the_declared_successor_is_admitted if {
	count(violation) == 0 with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": ["mise-tasks/wiring.sh"],
			"deleted": ["mise-tasks/old-gate.sh"],
			"base-lines": {"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "lint=\"$(dirname \"$0\")/mise-tasks/old-gate.sh\""]},
		},
		"lines": {
			"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "lint=\"$(dirname \"$0\")/policy/old-gate.rego\""],
			"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs"],
		},
	}}
}

# ANTI-VACUITY (a): the substitution must be EXACT. A line that repoints AND
# changes something else is an ordinary rewrite smuggled through a retirement.
test_a_repointing_that_also_changes_the_line_is_refused if {
	some v in violation with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": ["mise-tasks/wiring.sh"],
			"deleted": ["mise-tasks/old-gate.sh"],
			"base-lines": {"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "lint=mise-tasks/old-gate.sh"]},
		},
		"lines": {
			"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "lint=policy/old-gate.rego --force"],
			"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs"],
		},
	}}
	v.verdict == "V-SHELL-RULE-EDITED"
}

# ANTI-VACUITY (b): the target must be a successor the LEDGER declares, never one
# the editor picks. Without this the clause would admit repointing a caller at
# anything at all.
test_a_repointing_at_an_undeclared_target_is_refused if {
	some v in violation with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": ["mise-tasks/wiring.sh"],
			"deleted": ["mise-tasks/old-gate.sh"],
			"base-lines": {"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "lint=mise-tasks/old-gate.sh"]},
		},
		"lines": {
			"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "lint=mise-tasks/something-else.sh"],
			"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs"],
		},
	}}
	v.verdict == "V-SHELL-RULE-EDITED"
}

# ANTI-VACUITY (c): the retired path must be one THIS delta deleted, so a
# repointing cannot be spelled without actually retiring something.
test_a_repointing_away_from_a_live_path_is_refused if {
	some v in violation with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": ["mise-tasks/wiring.sh"],
			"deleted": ["mise-tasks/old-gate.sh"],
			"base-lines": {"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "lint=mise-tasks/still-here.sh"]},
		},
		"lines": {
			"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "lint=policy/old-gate.rego"],
			"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs"],
		},
	}}
	v.verdict == "V-SHELL-RULE-EDITED"
}

# COULD NOT LOOK REFUSES. A base side this could not read leaves the removed set
# unknowable, and an arm whose failure mode is a silent licence must fail closed.
test_an_edit_with_no_readable_base_side_is_refused if {
	some v in violation with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": ["mise-tasks/wiring.sh"],
			"deleted": ["mise-tasks/old-gate.sh"],
			"base-lines": {},
		},
		"lines": {
			"mise-tasks/wiring.sh": ["#!/usr/bin/env bash"],
			"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs"],
		},
	}}
	v.verdict == "V-SHELL-RULE-EDITED"
}

test_deleted_and_fully_mapped_passes if {
	count(violation) == 0 with input as {"tree": {
		"base-delta": {"added": [], "edited": [], "deleted": ["mise-tasks/old-gate.sh"]},
		"lines": {"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs"]},
	}}
}

test_deleted_without_a_mapping_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {"added": [], "edited": [], "deleted": ["mise-tasks/old-gate.sh"]},
		"lines": {},
	}}
}

test_deleted_with_two_arms_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {"added": [], "edited": [], "deleted": ["mise-tasks/old-gate.sh"]},
		"lines": {"crates/batten/tests/old_gate.rs": [
			"// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs",
			"// subsumed: mise-tasks/old-gate.sh policy/other.rego crates/batten/tests/other.rs",
		]},
	}}
}

test_mapping_without_a_policy_surface_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {"added": [], "edited": [], "deleted": ["mise-tasks/old-gate.sh"]},
		"lines": {"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh crates/batten/tests/old_gate.rs"]},
	}}
}

test_mapping_without_a_binary_test_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {"added": [], "edited": [], "deleted": ["mise-tasks/old-gate.sh"]},
		"lines": {"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego"]},
	}}
}

# --- the fourth arm (CLOUD-1080) --------------------------------------------
#
# The positive case: the subject dies in the same delta, the row carries a reason,
# and NO successor is named. Under the three-arm module this exact input raised
# both `V-SUCCESSOR-NO-SURFACE` and `V-SUCCESSOR-NO-TEST`, which is the refusal the
# arm exists to remove.
test_a_withdrawal_whose_subject_died_is_admitted if {
	count(violation) == 0 with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": [],
			"deleted": ["tests/old-gate.bats", ".claude/old-wrapper.sh"],
		},
		"lines": {"crates/batten/tests/old_gate.rs": ["// withdrawn: tests/old-gate.bats .claude/old-wrapper.sh the feature should not exist"]},
	}}
}

# THE DISCRIMINATING CASE, and the reason this arm is narrower than a waiver over
# the path: the subject is left STANDING while its suite is deleted and claimed
# withdrawn. Without this condition the arm admits every deletion, and the positive
# case above would pass against a module that decided nothing.
test_a_withdrawal_over_a_live_subject_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": [],
			"deleted": ["tests/old-gate.bats"],
		},
		"lines": {"crates/batten/tests/old_gate.rs": ["// withdrawn: tests/old-gate.bats .claude/old-wrapper.sh the feature should not exist"]},
	}}
}

# A row naming NOTHING but a reason is refused too, and this is the case that keeps
# `withdrawn_subjects` from being satisfiable by prose: every word on the row is a
# reason word, none of them names a deleted path, so the arm claims a withdrawal
# without retiring anything.
test_a_withdrawal_naming_no_retired_path_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": [],
			"deleted": ["tests/old-gate.bats", ".claude/old-wrapper.sh"],
		},
		"lines": {"crates/batten/tests/old_gate.rs": ["// withdrawn: tests/old-gate.bats the feature should not exist"]},
	}}
}

# It names no successor, so the reason is the only checkable thing on the row.
test_a_withdrawal_with_no_reason_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": [],
			"deleted": ["tests/old-gate.bats", ".claude/old-wrapper.sh"],
		},
		"lines": {"crates/batten/tests/old_gate.rs": ["// withdrawn: tests/old-gate.bats .claude/old-wrapper.sh"]},
	}}
}

# THE REGRESSION CASE for a defect found on review of this PR: with the retired
# path excluded from the SUBJECT set but not from the reason set, naming the dying
# file a second time satisfied both halves at once — a valid deleted subject, and
# the rejected word falling through as the prose. No reason is written here.
test_a_withdrawal_whose_only_reason_is_the_retired_path_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {"added": [], "edited": [], "deleted": ["tests/old-gate.bats", ".claude/old-wrapper.sh"]},
		"lines": {"crates/batten/tests/old_gate.rs": ["// withdrawn: tests/old-gate.bats .claude/old-wrapper.sh tests/old-gate.bats"]},
	}}
}

# The retired path itself is not its own subject. Without this a row could name the
# dying file again and satisfy the narrowing with the deletion it is excusing.
test_a_withdrawal_naming_only_itself_is_refused if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {"added": [], "edited": [], "deleted": ["tests/old-gate.bats"]},
		"lines": {"crates/batten/tests/old_gate.rs": ["// withdrawn: tests/old-gate.bats tests/old-gate.bats a reason"]},
	}}
}

# The three successor-naming arms are untouched by the fourth: one of them over a
# row naming no policy surface still refuses, so the exemption is scoped to
# `withdrawn` rather than switched on for every deletion.
test_the_successor_obligation_still_binds_the_other_arms if {
	count(violation) == 1 with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": [],
			"deleted": ["tests/old-gate.bats", ".claude/old-wrapper.sh"],
		},
		"lines": {"crates/batten/tests/old_gate.rs": ["// carried: tests/old-gate.bats crates/batten/tests/old_gate.rs"]},
	}}
}

# --- the subject condition, on all four arms (CLOUD-1130) --------------------
#
# A suite retired onto real successors while the program it tested stands
# untouched. Under the three-arm module this input raised nothing at all: every
# successor obligation is satisfied, and the subject-alive condition was reachable
# only behind `withdrawn_arm`.
test_a_carried_row_naming_a_live_subject_is_refused if {
	some v in violation with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": [],
			"deleted": ["tests/old-gate.bats"],
		},
		"lines": {"crates/batten/tests/old_gate.rs": ["// carried: tests/old-gate.bats mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs"]},
	}}
	v.verdict == "V-RETIREMENT-SUBJECT-ALIVE"
}

# THE OTHER DIRECTION, and without it the arm above would be a ban on naming a
# subject at all. The same row, with the subject retired in the same delta and
# carrying its own arm, is a conforming whole retirement and passes.
test_a_row_whose_named_subject_died_is_admitted if {
	count(violation) == 0 with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": [],
			"deleted": ["tests/old-gate.bats", "mise-tasks/old-gate.sh"],
		},
		"lines": {"crates/batten/tests/old_gate.rs": [
			"// carried: tests/old-gate.bats mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs",
			"// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs",
		]},
	}}
}

# AND A REASON IS NEVER A SUBJECT EITHER. A `changed` arm's tail carries prose
# after its two successors, so a sentence mentioning the governed program this
# migration deliberately left standing must not read as a claim about it. Without
# the marker bound in `named_and_alive` this input raises
# `V-RETIREMENT-SUBJECT-ALIVE` over a word in an explanation — a false refusal in
# the gate every retirement in CLOUD-843's campaign has to pass.
test_a_changed_reason_naming_a_governed_path_is_not_a_subject if {
	count(violation) == 0 with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": [],
			"deleted": ["tests/old-gate.bats"],
		},
		"lines": {"crates/batten/tests/old_gate.rs": ["// changed: tests/old-gate.bats policy/old-gate.rego crates/batten/tests/old_gate.rs the assertion mise-tasks/other-gate.sh made about untracked files is deliberately inverted here"]},
	}}
}

# AND THE WITHDRAWAL KEEPS ITS OWN ARM rather than gaining a second reading. Its
# reason is prose on the same footing, and `V-WITHDRAWAL-SUBJECT-ALIVE` already
# decides whether its subject survived — from `withdrawn_subjects`, which requires
# a named path to be in THIS delta's deleted set.
test_a_withdrawal_reason_naming_a_governed_path_is_not_a_subject if {
	count(violation) == 0 with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": [],
			"deleted": ["tests/old-gate.bats", "mise-tasks/old-gate.sh"],
		},
		"lines": {"crates/batten/tests/old_gate.rs": [
			"// withdrawn: tests/old-gate.bats mise-tasks/old-gate.sh the shape mise-tasks/other-gate.sh still guards should never have had a suite of its own",
			"// withdrawn: mise-tasks/old-gate.sh tests/old-gate.bats the shape mise-tasks/other-gate.sh still guards should never have had a program of its own",
		]},
	}}
}

# AND A SUCCESSOR IS NEVER A SUBJECT. `policy/*.rego` and `crates/batten/tests/*.rs`
# are ungoverned by construction, so the ordinary mapping — which names nothing
# else — cannot trip the arm. This is `test_deleted_and_fully_mapped_passes` read
# from the new condition's side.
test_a_mapping_naming_only_successors_is_untouched if {
	count(violation) == 0 with input as {"tree": {
		"base-delta": {"added": [], "edited": [], "deleted": ["tests/old-gate.bats"]},
		"lines": {"crates/batten/tests/old_gate.rs": ["// carried: tests/old-gate.bats policy/old-gate.rego crates/batten/tests/old_gate.rs"]},
	}}
}

# The anti-vacuity arm on the OTHER axis: an untouched tree, and a generated or
# non-shell path moving, must both be silent. Without this a module that refused
# everything would still pass every case above.
test_an_untouched_tree_is_silent if {
	count(violation) == 0 with input as {"tree": {
		"base-delta": {"added": [], "edited": [], "deleted": []},
		"lines": {},
	}}
}

test_a_non_shell_path_is_not_governed if {
	count(violation) == 0 with input as {"tree": {
		"base-delta": {
			"added": ["completions/batten.bash"],
			"edited": ["mise-tasks/replay-pointers.py", "crates/batten/src/lib.rs"],
			"deleted": ["mise-tasks/sbom-actions.tsv"],
		},
		"lines": {},
	}}
}

# A base that did not resolve is could-not-look: no findings, and deliberately
# not the same answer as a clean tree, because the engine emits `null` there and
# every predicate above is undefined rather than false.
test_an_unresolvable_base_reports_nothing if {
	count(violation) == 0 with input as {"tree": {"base-delta": null, "lines": {}}}
}

# --- CLOUD-1149 / CLOUD-1219: the sibling spelling and the invocation successor.

# The removal side, with NO repo-relative path anywhere on the line. This is the
# shape `contains(line, gone)` could not see, and it is 41 call sites.
test_dropping_a_sibling_resolution_is_admitted if {
	count(violation) == 0 with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": ["mise-tasks/wiring.sh"],
			"deleted": ["mise-tasks/old-gate.sh"],
			"base-lines": {"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "lint=\"$(dirname \"$0\")/old-gate.sh\""]},
		},
		"lines": {
			"mise-tasks/wiring.sh": ["#!/usr/bin/env bash"],
			"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs"],
		},
	}}
}

# THE SHAPE THAT MOTIVATED BOTH ROWS: the callee is bound once and spent later as
# a single word, so repointing onto a verb changes the call's ARITY and the spend
# line names no retired path at all.
test_a_variable_borne_caller_repointed_at_a_declared_invocation_is_admitted if {
	count(violation) == 0 with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": ["mise-tasks/wiring.sh"],
			"deleted": ["mise-tasks/old-gate.sh"],
			"base-lines": {"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "lint=\"$(dirname \"$0\")/old-gate.sh\"", "printf x | \"$lint\" 2>/dev/null"]},
		},
		"lines": {
			"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "printf x | mise run old-gate 2>/dev/null"],
			"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs runs:mise+run+old-gate"],
		},
	}}
}

# ANTI-VACUITY: the invocation must be one the LEDGER declares. Without this the
# case above is satisfied by a clause that admits anything.
test_a_repointing_at_an_undeclared_invocation_is_refused if {
	some v in violation with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": ["mise-tasks/wiring.sh"],
			"deleted": ["mise-tasks/old-gate.sh"],
			"base-lines": {"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "lint=\"$(dirname \"$0\")/old-gate.sh\"", "printf x | \"$lint\" 2>/dev/null"]},
		},
		"lines": {
			"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "printf x | mise run something-else 2>/dev/null"],
			"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs runs:mise+run+old-gate"],
		},
	}}
	v.verdict == "V-SHELL-RULE-EDITED"
}

# THE LOAD-BEARING NEGATIVE. Without the "span is a reference to a deleted path"
# conjunct, the prefix/suffix decomposition admits replacing ANY contiguous span
# of ANY line that accompanies a deletion. `$REPO_ROOT` is not this script's
# directory, so the span names somebody else's tree.
test_replacing_a_span_that_is_not_a_retired_reference_is_refused if {
	some v in violation with input as {"tree": {
		"base-delta": {
			"added": [],
			"edited": ["mise-tasks/wiring.sh"],
			"deleted": ["mise-tasks/old-gate.sh"],
			"base-lines": {"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "REPO_ROOT=/srv/build", "payload=\"$REPO_ROOT/tools/old-gate.sh\""]},
		},
		"lines": {
			"mise-tasks/wiring.sh": ["#!/usr/bin/env bash", "REPO_ROOT=/srv/build", "payload=mise run old-gate"],
			"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh policy/old-gate.rego crates/batten/tests/old_gate.rs runs:mise+run+old-gate"],
		},
	}}
	v.verdict == "V-SHELL-RULE-EDITED"
}

# THE FIELD IS ADDITIVE: it satisfies neither successor obligation, so it cannot
# become a cheaper way past the two clauses that make a retirement owe a module
# and a compiled-binary test.
test_an_invocation_field_is_not_a_successor if {
	some v in violation with input as {"tree": {
		"base-delta": {"added": [], "edited": [], "deleted": ["mise-tasks/old-gate.sh"], "base-lines": {}},
		"lines": {"crates/batten/tests/old_gate.rs": ["// carried: mise-tasks/old-gate.sh runs:mise+run+old-gate"]},
	}}

	# `V-SUCCESSOR-NO-SURFACE`, never `V-RETIREMENT-UNMAPPED`: the arm EXISTS and
	# is mapped, so what it fails is the successor obligation rather than the
	# mapping one. Naming the wrong verdict here was this case's own first defect,
	# and it would have passed over a module refusing for a different reason.
	v.verdict == "V-SUCCESSOR-NO-SURFACE"
}
