//! Price inline versus addressed transport over a payload corpus (CLOUD-1367).
//!
//! # A report, never a gate
//!
//! Nothing in `verify` or the hk gate calls this, for `acquisition-bench`'s
//! reason exactly: it answers a question about a MEASUREMENT rather than about a
//! commit, and a number that moves with the corpus has no business deciding
//! whether a tree lands. It writes `bench/address-transport/RESULTS.md` and exits
//! 0 whatever the numbers say.
//!
//! # An example target rather than a verb
//!
//! `crates/batten/tests/pointer_only.rs` sweeps every leaf verb over a bare
//! fixture corpus and refuses one that exits 3 — and a bench with no corpus to
//! price has could-not-look as its only honest answer there. `acquisition-bench`
//! records that reasoning at its own site; this follows it rather than inventing
//! a SKIP predicate to satisfy a census.
//!
//! # What is priced
//!
//! The ACTUAL rendered grammar: `identity::ADDRESS_RENDERED_LEN`, which includes
//! the `b3-` tag, the version and both separators. §2 rules out a generic hash
//! length or a bytes-over-four approximation, and reading the constant rather
//! than restating it is what keeps this from becoming a second authority over the
//! grammar.
//!
//! Token counts are reported as CHARACTERS, and the header says so. A tokenizer
//! is provider- and model-specific; claiming token counts without one would be
//! the approximation §2 refuses, wearing a more precise-looking unit.

use std::fmt::Write as _;

use batten::capture::{DEFAULT_INLINE_MAX_BYTES, Transport, transport_for};
use batten::identity::{ADDRESS_RENDERED_LEN, AddressDomain, ContentAddress};

/// One corpus entry: a name and a payload size in bytes.
const CORPUS: &[(&str, usize)] = &[
    ("tiny", 64),
    ("small", 512),
    ("threshold-under", DEFAULT_INLINE_MAX_BYTES as usize),
    ("threshold-over", DEFAULT_INLINE_MAX_BYTES as usize + 1),
    ("medium", 16 * 1024),
    ("large", 512 * 1024),
    ("huge", 4 * 1024 * 1024),
];

/// How many times a payload is read, for the reuse arm.
const REUSE: &[(&str, usize)] = &[("one-shot", 1), ("repeated", 8)];

fn main() -> std::io::Result<()> {
    let mut out = String::new();
    out.push_str("# Address versus inline transport\n\n");
    out.push_str(
        "Generated by `mise run address-transport-bench`. A REPORT, never a gate: no task in \
         `verify` or the hk gate reads it, and it exits 0 whatever the numbers say.\n\n",
    );
    let _ = writeln!(
        out,
        "Sizes are CHARACTERS emitted, not tokens. A tokenizer is provider- and \
         model-specific, and reporting characters is the honest unit available here — \
         CLOUD-1367 §2 rules out a bytes-over-four approximation, and inventing one under a \
         token label would be that approximation with a better name.\n"
    );
    let _ = writeln!(
        out,
        "An address costs a fixed **{ADDRESS_RENDERED_LEN} characters** — the rendered \
         grammar including `b3-`, the version and both separators, read from \
         `identity::ADDRESS_RENDERED_LEN` rather than restated.\n"
    );
    let _ = writeln!(
        out,
        "The declared threshold is `[capture] inline_max_bytes`, defaulting to \
         **{DEFAULT_INLINE_MAX_BYTES}**. At or under it a payload renders inline; over it, \
         addressed.\n"
    );

    out.push_str("## One-shot and repeated reads\n\n");
    out.push_str(
        "| payload | bytes | reuse | transport | emitted | inline would emit | saved |\n\
         | ------- | ----- | ----- | --------- | ------- | ----------------- | ----- |\n",
    );

    for (name, size) in CORPUS {
        let payload = vec![b'x'; *size];
        let address = ContentAddress::of(AddressDomain::Capture, &payload);
        let rendered = address.render();
        debug_assert_eq!(rendered.len(), ADDRESS_RENDERED_LEN);

        for (shape, reads) in REUSE {
            let transport = transport_for(None, *size as u64);
            // THE ADDRESS IS SENT ONCE AND RESOLVED PER READ; the inline arm
            // re-sends the payload every time. That asymmetry is the whole
            // economic case, and pricing a single read would hide it.
            let emitted = match transport {
                Transport::Inline => size * reads,
                Transport::Addressed => ADDRESS_RENDERED_LEN * reads,
            };
            let inline_would = size * reads;
            let saved = inline_would.saturating_sub(emitted);
            let _ = writeln!(
                out,
                "| {name} | {size} | {shape} ({reads}x) | {} | {emitted} | {inline_would} | {saved} |",
                transport.as_str()
            );
        }
    }

    out.push_str(
        "\n## What is NOT priced here, and why it is not an omission\n\n\
         * **Store and index writes, eviction misses and retries.** Those are costs in \
         the store's own currency — bytes on disk and a filesystem round trip — and \
         folding them into a character count would produce one number that is honest \
         about neither. They belong beside `acquisition-bench`'s reading.\n\
         * **Privacy and safety caps.** They refuse to emit content at all, where this \
         only changes the representation. One number serving both would let a \
         measurement about cost decide what may leave the process.\n\
         * **A tokenizer.** See the header: characters are what can be measured without \
         claiming a provider's tokenization.\n",
    );

    let dir = std::path::Path::new("bench/address-transport");
    std::fs::create_dir_all(dir)?;
    std::fs::write(dir.join("RESULTS.md"), out)?;
    println!("address-transport-bench: bench/address-transport/RESULTS.md written");
    Ok(())
}
